"use strict";
(()=>{
const $=id=>document.getElementById(id);let state,busy=false,chosen=null,draft=null;
const labels={open:'Faux',true:'Vrai',declared:'Révélation demain',preparing:'En préparation',ready:'À examiner le soir',acquired:'Acquis constaté',active:'Actif',resolved:'Réalisée',failed:'Échec',removed:'Levé'},icons={state:'🎯',key:'🗝️',lock:'🔒',attack:'⚔️'};
const byId=id=>state.nodes.find(n=>n.id===id)||state.resources.find(r=>r.id===id),own=n=>n.owner==='phoebe',free=r=>own(r)&&r.availability==='free',paid=()=>!busy&&state.phase==='player'&&!state.spent.phoebe&&state.day<state.finalDay;
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function button(text,fn,disabled=false,cls=''){const b=el('button',cls,text);b.type='button';b.disabled=disabled;b.onclick=fn;return b;}
function notify(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function cardText(n){if(n.availability)return n.description+'\n\n'+({subject:'Personne à protéger ; son concours doit être établi.',free:'Disponible',recovering:'Récupération · réutilisable au jour '+n.recoveryUntil,incoming:'Retour ou arrivée au jour '+n.availableDay,preparing:'Préparation jusqu’au jour '+n.availableDay,engaged:'Engagée dans '+(byId(n.heldBy)?.title||n.heldBy),frozen:'Engagée dans une contribution suspendue par une question.',lost:n.consumed?'Consommée':'Perdue'})[n.availability];
 const lines=[n.description||n.title];if(n.type==='state')lines.push('État actuel : '+(n.status==='true'?'vrai':'faux')+(n.goalMode==='maintain'?' · à maintenir jusqu’à l’échéance.':'.'));if(n.established)lines.push('Fait obtenu : '+n.established);else if(n.effect)lines.push('Contribution visée : '+n.effect);if(n.discovery&&n.type!=='attack')lines.push('Contribution à examiner en fin de journée. Vous pouvez la renforcer avec une ressource pertinente.');if(n.type==='attack'&&n.requiredCount)lines.push('Nombre de ressources : '+n.requiredCount);if(n.dueDay)lines.push(n.reactionThroughDay!==undefined?'Examen au soir du jour '+n.dueDay+' au plus tôt ; annonce au matin du jour '+(n.dueDay+1)+'.':'Réalisation : matin du jour '+n.dueDay);if(n.risks)lines.push('Risques : '+n.risks);if(n.suspended)lines.push('Justification en attente : action suspendue.');if(n.blockedBy?.length)lines.push('Effet bloqué par un verrou.');return lines.join('\n\n');}
function attacking(r){return state.nodes.find(n=>n.type==='attack'&&n.target===r.id&&!['failed','resolved','removed'].includes(n.status));}
function retained(r){return r.heldBy&&byId(r.heldBy)?.status==='acquired';}
function canQuestion(n){return !own(n)&&['key','lock','state'].includes(n.type)&&!['failed','removed'].includes(n.status)&&!state.questions.some(q=>q.target===n.id);}
function modes(n){const a=[];if((n.type==='state'&&own(n))||(n.type==='lock'&&!own(n)&&['ready','active'].includes(n.status)))a.push('key');if(!own(n)&&((['state','key','attack'].includes(n.type)&&!['failed','removed','resolved'].includes(n.status))||(n.availability&&n.heldBy&&n.availability!=='lost')))a.push('lock');return a;}
// Une carte qui ne reçoit aucune pose ne doit pas rester muette : on dit
// pourquoi, et par où passer à la place.
function poseImpossible(n){
 if(n.type==='lock'&&!own(n))return 'Ce verrou n’est plus contestable : la contre-clé se forme tant qu’il est prêt ou actif.';
 if(n.type==='lock'&&own(n))return 'C’est votre propre verrou : vous le renforcez tant qu’il est en préparation, vous ne l’ouvrez pas.';
 if(['failed','removed','resolved'].includes(n.status))return 'Cette carte est terminée : elle ne reçoit plus de pose.';
 if(own(n))return 'Cette carte est à vous et n’est plus en préparation : elle ne reçoit plus de renfort.';
 return 'Cette carte ne reçoit pas de pose dans son état actuel.';
}
function autresVoies(n){
 return state.resources.filter(r=>!own(r)&&r.heldBy===n.id&&r.availability!=='lost')
  .map(r=>'Verrouiller « '+r.title+' », la ressource que cette carte engage : ouvrez la carte de cette ressource et posez-y une des vôtres.');
}
function preparing(n){return own(n)&&['key','lock','attack'].includes(n.type)&&(['preparing','declared'].includes(n.status)||(n.type!=='attack'&&n.status==='ready'))&&!n.suspended&&(n.type!=='attack'||(state.day>=n.revealDay&&state.day<n.dueDay));}
function writingHelp(kind){
 const sub=kind==='subgoal',pose=['key','lock','place'].includes(kind);
 $('writing-help').hidden=!sub&&!pose;
 $('writing-help-title').textContent=sub?'Définir le résultat à obtenir':'Expliquer le moyen que tu engages';
 const questions=sub?['Quelle affirmation veux-tu rendre vraie ?','Pourquoi aiderait-elle ton état initial ?']:['Que veux-tu faire avec cette ressource ?','Comment, sur quelle cible et pour obtenir quel effet précis ?'];
 $('writing-questions').replaceChildren(...questions.map(t=>el('li','',t)));
 $('writing-reminder').textContent=sub?'Écris une affirmation constatable, pas une action. Sa création ne la rend pas vraie : les clés devront en apporter les preuves.':kind==='place'?'Explique ce que cette ressource apporte à la préparation existante, sans changer son effet visé.':'Tu proposes un moyen d’agir. L’Ange du destin formule la clé ou le verrou et indique combien de ressources manquent et si un délai est nécessaire.';
 if(sub||pose)$('text-label').firstChild.textContent='Ta proposition';
}
function openDraft(kind,target=null,rid=null){$('detail').close();$('action-form').hidden=false;$('receipt').hidden=true;draft={kind,target,resource:rid};$('proposal').value='';$('text-label').firstChild.textContent=kind==='subgoal'?'Quelle affirmation doit devenir vraie, et pourquoi sert-elle votre état initial ?':'Qui ou quoi, comment et dans quel but ?';$('proposal').placeholder=kind==='subgoal'?'Écris une phrase constatable, puis explique son intérêt pour ton objectif.':'Décris précisément ton action et l’effet recherché…';$('effect-label').hidden=!['key','lock'].includes(kind);if(['key','lock'].includes(kind)){$('effect-kind').replaceChildren(...modes(byId(target)).map(k=>{const o=el('option','',k==='key'?'Clé — rendre vrai ou lever un verrou':'Verrou — bloquer un effet précis');o.value=k;return o;}));$('effect-kind').value=kind;}
 $('composer-title').textContent=({key:'Poser cette ressource',lock:'Poser cette ressource',place:'Engager cette ressource dans la préparation',defend:'Renforcer la cible de l’attaque',attack:'Déclarer une attaque ou un vol',subgoal:'Définir ce sous-objectif',resource:'Créer une ressource',question:'Demander une justification',answer:'Répondre à la question'})[kind];const q=kind==='answer'?state.questions.find(q=>q.id===target):null;$('composer-context').textContent=q?q.text:[rid?byId(rid)?.title:null,target?byId(target)?.title:null].filter(Boolean).join(' → ');
 $('cost').textContent=kind==='attack'?'Acceptée : la tentative engage votre coup. Moyens et date révélés demain matin. Aucun abandon.':kind==='defend'?'Un coup si accepté. La ressource restera engagée jusqu’à la résolution de l’attaque.':['question','answer','resource'].includes(kind)?'Gratuit. La proposition est examinée par l’Ange du destin.':kind==='subgoal'?'Créer ce sous-état consomme ton coup du tour s’il est accepté et occupe un emplacement. Cela n’engage aucune ressource et ne réalise encore aucun effet.':'Un coup si accepté. Une ressource engagée ; la carte se place à côté de sa cible.';$('submit').textContent=kind==='question'?'Poser la question':kind==='answer'?'Soumettre la réponse':'Soumettre à l’Ange du destin';writingHelp(kind);$('composer').showModal();setBusy(busy);$('proposal').focus();}
function pose(n,rid){if(!paid())return notify('Vous devez disposer de votre coup pendant votre passage.',true);if(!free(byId(rid)))return notify('Cette ressource est indisponible.',true);if(preparing(n))return openDraft('place',n.id,rid);const allowed=modes(n);if(!allowed.length)return notify(poseImpossible(n)+(autresVoies(n)[0]?' '+autresVoies(n)[0]:' Ouvrez sa carte : les voies possibles y sont indiquées.'),true);openDraft(allowed[0],n.id,rid);}
function showDetail(n){if(chosen&&(!n.availability||(!own(n)&&modes(n).includes('lock')))){pose(n,chosen);return;}if(n.type==='state'&&!n.parent)return showRootBook(n);$('detail').className='card-detail detail-'+(n.availability?(['key','lock'].includes(byId(n.heldBy)?.type)?byId(n.heldBy).type:'resource'):n.type);$('detail-title').textContent=n.title;$('detail-text').textContent=cardText(n);const actions=$('card-actions');actions.replaceChildren();if(n.availability){if(free(n))actions.append(button('Choisir cette ressource à poser',()=>{chosen=n.id;$('detail').close();render();notify(n.title+' choisie. Cliquez sur sa cible.');},!paid()));if(own(n)&&n.heldBy&&['key','lock'].includes(byId(n.heldBy)?.type))actions.append(button('Retirer de cette contribution',()=>{$('detail').close();run({type:'withdraw',resource:n.id});},!paid()));if(!own(n)&&n.availability!=='lost')actions.append(button('Attaquer / voler cette cible',()=>openDraft('attack',n.id),!paid()||!state.resources.some(free)));
 // Consulter un document qu'on détient : gratuit, sans examen ni délai.
 if(own(n)&&n.document&&!(n.consultedBy||[]).includes('phoebe'))actions.append(button('📖 Consulter ce document (gratuit)',()=>{$('detail').close();run({type:'consult',resource:n.id});},busy||state.phase!=='player'));
 if(own(n)&&n.document&&(n.consultedBy||[]).includes('phoebe'))actions.append(el('p','','Document déjà consulté : son contenu figure dans le fil de l’Ange du destin.'));}else{if(modes(n).length||preparing(n)){const list=el('div','resource-picker');list.append(el('p','','Poser une ressource sur cette cible :'));state.resources.filter(free).forEach(r=>list.append(button((r.icon||'📦')+' '+r.title,()=>pose(n,r.id),!paid())));actions.append(list);}else{const info=el('div','resource-picker');info.append(el('p','',poseImpossible(n)));const voies=autresVoies(n);if(voies.length){info.append(el('p','','Par où passer :'));const ul=el('ul','');voies.forEach(t=>ul.append(el('li','',t)));info.append(ul);}actions.append(info);}if(n.type==='attack'&&!own(n)&&state.day>=n.revealDay&&state.day<n.dueDay){const defense=el('div','resource-picker');defense.append(el('p','','Renforcer directement la cible :'));state.resources.filter(free).forEach(r=>defense.append(button((r.icon||'📦')+' '+r.title,()=>openDraft('defend',n.id,r.id),!paid())));actions.append(defense);}if(canQuestion(n))actions.append(button('❓ Poser une question sur cette action',()=>openDraft('question',n.id),busy||state.phase!=='player'));for(const q of state.questions.filter(q=>q.target===n.id&&!q.resolved)){actions.append(el('p','question',q.text));if(own(n)&&q.answer===null)actions.append(button('Répondre à cette question',()=>openDraft('answer',q.id),busy||state.phase!=='player'));}}$('detail').showModal();}
function illustratedDialog(kind){
 let d=$('illustrated-detail');if(!d){d=el('dialog','');d.id='illustrated-detail';document.body.append(d);}
 d.className=kind;d.replaceChildren();const close=button('×',()=>d.close(),false,'close');close.setAttribute('aria-label','Fermer');d.append(close);return d;
}
function showRootBook(n){
 const d=illustratedDialog('root-book'),left=el('section','book-page'),right=el('section','book-page');
 left.append(el('p','book-kicker','Objectif initial'),el('h2','book-title',shortTitle(n)),el('p','truth-pill',(n.status==='true'?'Vrai':'Faux')+(n.goalMode==='maintain'?' · À maintenir':'')),el('h3','','Énoncé complet'),el('p','book-statement',n.description||n.title));
 const fixedTitle=el('img','book-fixed-objective');fixedTitle.src='/modules/charmed-assets/livre-titre-objectif.png';fixedTitle.alt='Objectif initial';left.firstChild.replaceWith(fixedTitle);
 const divider=el('img','book-divider');divider.src='/modules/charmed-assets/livre-separateur.png';divider.alt='';left.append(divider);
 if(n.goalMode==='maintain')left.append(el('p','book-deadline','Échéance : matin du jour '+state.finalDay));
 if(n.suspended)left.append(el('p','','Justification en attente.'));
 right.append(el('h2','',own(n)?'Poser une ressource':'Poser un verrou'),el('p','','Choisis une ressource à engager sur cet objectif.'));
 if(own(n)){const fixed=el('img','book-fixed-resource');fixed.src='/modules/charmed-assets/livre-titre-ressource.png';fixed.alt='Poser une ressource. Choisis une ressource à engager sur cet objectif.';right.replaceChildren(fixed);}
 const picker=el('div','book-resources');for(const r of state.resources.filter(free)){const b=button(r.title,()=>{d.close();pose(n,r.id);},!paid(),'book-resource');b.setAttribute('aria-label','Engager '+r.title);picker.append(b);}
 if(canQuestion(n))right.append(button('Poser une question',()=>{d.close();openDraft('question',n.id);},busy||state.phase!=='player'));for(const q of state.questions.filter(q=>q.target===n.id)){right.append(button(q.answer?'Lire la réponse':'Lire la question',()=>{d.close();showQuestion(q);}));}right.append(picker);if(!picker.children.length)right.append(el('p','','Aucune ressource disponible.'));
 right.append(el('p','book-help','Tu préciseras ensuite son action et l’effet recherché.'),button('Fermer',()=>d.close(),false,'book-return'));d.append(left,right);d.showModal();
}
function showCalendarEvent(day,events,index=0){
 const d=illustratedDialog('calendar-parchment'),e=events[index];
 const heading=el('h2','founders-heading','Les Fondateurs');d.append(heading,el('p','book-kicker','Calendrier de la partie'));
 if(/manoir|rue|boîte|travaux/i.test((e?.title||'')+' '+(e?.text||''))){const photo=el('img','event-photo');photo.src='/modules/charmed-assets/manoir-evenement.png';photo.alt='Le manoir Halliwell';d.append(photo);}
 d.append(el('p','event-day','Jour '+day),el('h3','event-title',e?.title||'Aucun événement annoncé'),el('p','event-text',e?e.text.replace(e.title,'').trim().split('\n\n').filter((line,i,lines)=>i===0||!lines.slice(0,i).some(previous=>line.endsWith(': '+previous))).join('\n\n'):'Aucun événement n’est annoncé pour cette journée.'));
 if(events.length>1){const nav=el('div','event-navigation');nav.append(button('←',()=>showCalendarEvent(day,events,index-1),index===0),el('span','',(index+1)+' / '+events.length),button('→',()=>showCalendarEvent(day,events,index+1),index===events.length-1));d.append(nav);}
 d.append(button('Revenir au plateau',()=>d.close(),false,'book-return'));if(!d.open)d.showModal();
}
function art(n){
 const box=el('span','symbol');
 const text=(n.title+' '+(n.category||'')).toLowerCase();
 let path='M7 8h18v18H7z M7 8l9-5 9 5 M16 13v13 M7 8l9 5 9-5';
 if(n.type==='state')path='M16 3C3 13 2 25 16 23C30 25 29 13 16 3Z M5 25C20 29 30 20 21 10C15-2 4 8 5 25Z M27 25C28 8 17-2 11 10C2 20 12 29 27 25Z';
 else if(n.type==='attack')path='M5 3l24 24 M27 3L3 27 M3 21l8 8 M21 3l8 8';
 else if(n.type==='lock')path='M7 14h18v15H7z M10 14V9a6 6 0 0 1 12 0v5 M16 19v5';
 else if(/invitation|lettre|convocation|programme|document/.test(text))path='M3 7h26v19H3z M3 7l13 11L29 7 M3 26l9-12 M29 26l-9-12';
 else if(/livre|carnet|notes|formule/.test(text))path='M16 8Q9 3 3 6v21q7-3 13 1q6-4 13-1V6q-6-3-13 2v20 M7 11l5 1 M20 12l5-1';
 else if(/potion|flacon/.test(text))path='M12 3h8 M13 3v10L6 24q-2 5 4 5h12q6 0 4-5l-7-11V3 M9 20h14';
 else if(/lieu|chambre|maison|manoir|galerie|refuge/.test(text))path='M3 14L16 3l13 11 M6 12v17h20V12 M13 29V18h6v11';
 else if(/protec|sécur|garde/.test(text))path='M16 3L4 8v9q0 8 12 13q12-5 12-13V8Z M10 16l4 4 8-9';
 else if(/parl|confiance|conversation|dialogue|accord/.test(text))path='M3 5h26v17H15l-8 7v-7H3Z M8 11h16 M8 16h10';
 else if(n.type==='key')path='M21 3a7 7 0 1 0 0 14a7 7 0 0 0 0-14 M16 15L3 28 M6 25l4 4 M10 21l4 4';
 box.innerHTML='<svg viewBox="0 0 32 32" aria-hidden="true"><path d="'+path+'" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/></svg>';
 return box;
}
function shortTitle(n){
 const t=n.title||'';if(n.category==='personnage')return t;
 const explicit=n.displayTitle||n.shortTitle;if(explicit&&explicit.length<=38)return explicit;
 const rules=[
 [/vivante.*meurtre/i,'Survie d’Élise'],[/Élise est morte/i,'Mort d’Élise'],
 [/fait confiance.*accepte/i,'Confiance et protection'],[/Nina.*accepté.*rejoindre/i,'Accord de Nina'],
 [/Élise est présente.*rendez-vous/i,'Élise au rendez-vous'],[/remise.*convocation/i,'Remise de la convocation'],
 [/constater.*entrée.*Élise/i,'Entrée d’Élise'],[/Nina parle.*accompagne/i,'Rencontre avec Phoebe'],
 [/regrouper.*informations/i,'Recoupement des informations'],[/tentative.*agression/i,'Agression contre Élise'],
 [/programme public.*réception/i,'Programme public'],[/carnet de la vision/i,'Carnet de vision'],
 [/invitation d’Élise/i,'Invitation d’Élise'],[/chambre chez Nina/i,'Chambre de Nina']
 ];for(const [pattern,label] of rules)if(pattern.test(t))return label;
 if(t.length<=34)return t;
 // Display label only: preserve the complete original statement in the detail dialog.
 const words=t.replace(/^(Je (?:déclare|propose|pose|souhaite) |Pour |En préparation\s*:\s*)/i,'').replace(/[.,;:].*$/,'').split(/\s+/);
 let label='';for(const word of words){if((label+' '+word).trim().length>34)break;label+=(label?' ':'')+word;if(label.split(' ').length>=5)break;}return label||t.split(/\s+/)[0];
}
function showQuestion(q){$('detail-title').textContent=q.resolved?'Question traitée':q.answer?'Réponse enregistrée · examen ce soir':'Question en attente';$('detail-text').textContent='Sur : '+byId(q.target).title+'\n\nQUESTION\n'+q.text+'\n\nRÉPONSE\n'+(q.answer||'Aucune réponse pour le moment.')+(q.reason?'\n\nDÉCISION DE L’ARBITRE\n'+q.reason:'');$('card-actions').replaceChildren();if(!q.resolved&&q.answer===null&&own(byId(q.target)))$('card-actions').append(button('Répondre à cette question',()=>openDraft('answer',q.id),busy||state.phase!=='player'));$('detail').showModal();}
function makeCard(n){const type=n.type||'resource',b=button('',()=>showDetail(n),false,'card '+type);b.dataset.id=n.id;b.setAttribute('aria-label',n.title+' — '+(n.availability||labels[n.status]||''));if(['preparing','declared'].includes(n.status)||['incoming','preparing'].includes(n.availability))b.classList.add('pending');if(['frozen','lost','engaged','recovering'].includes(n.availability))b.classList.add('unavailable');if(n.availability==='lost')b.classList.add('lost');if(n.suspended)b.classList.add('suspended');if(n.status==='acquired')b.classList.add('evidence');if(n.type==='state'&&!n.parent)b.classList.add('root-card');if(n.category==='personnage')b.classList.add('person-card');if(chosen===n.id)b.classList.add('selected-resource');const inner=el('span','card-inner'),front=el('span','face front'),back=el('span','face back');front.append(el('span','short',shortTitle(n)));let status=n.availability?({subject:'À protéger',free:'',recovering:'Repos · J'+n.recoveryUntil,incoming:'⏳ J'+n.availableDay,preparing:'⌛ J'+n.availableDay,engaged:'',frozen:'',lost:'Perdue'})[n.availability]:labels[n.status];if(n.status==='removed'&&n.type==='key')status='Retirée';if(n.effectUnavailable)status='Effet indisponible';else if(n.suspended)status='Suspendue';else if(n.blockedBy?.length)status='🔒 Bloquée';else if(n.type==='attack'&&n.requiredCount&&['preparing','ready','declared'].includes(n.status))status=n.pieces.length+'/'+n.requiredCount+(n.dueDay?' · J'+n.dueDay:'');if(n.status==='ready'&&n.reactionThroughDay!==undefined&&!n.suspended&&!n.blockedBy?.length)status='Examen soir J'+n.dueDay;front.append(el('span','status',n.status==='acquired'?'⚿ ✓ Acquise':status));inner.append(front);b.append(inner);const q=state.questions.find(q=>q.target===n.id);if(q){const badge=el('span','question-badge'+(q.resolved?' answered':''),q.resolved?'? ✓':'?');badge.setAttribute('role','button');badge.tabIndex=0;badge.setAttribute('aria-label',q.resolved?'Lire la question et sa réponse':'Lire la question sans réponse');badge.onclick=e=>{e.stopPropagation();showQuestion(q);};badge.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();showQuestion(q);}};b.append(badge);}else if(n.suspended)b.append(el('span','question-badge inherited','?'));
 if(n.availability&&free(n)){b.draggable=paid();b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',n.id));}if(!n.availability){b.addEventListener('dragover',e=>{if(paid()){e.preventDefault();b.classList.add('drop-active');}});b.addEventListener('dragleave',()=>b.classList.remove('drop-active'));b.addEventListener('drop',e=>{e.preventDefault();b.classList.remove('drop-active');const rid=e.dataTransfer.getData('text/plain');if(state.resources.some(r=>r.id===rid&&free(r)))pose(n,rid);});}return b;}
function visibleNode(n){return n.status!=='removed'||n.type==='lock'&&state.nodes.some(k=>k.target===n.id&&k.status==='acquired');}
function branchFor(n){const seen=new Set();let t=byId(n.target);while(t&&t.type!=='state'&&!seen.has(t.id)){seen.add(t.id);t=byId(t.target);}return t?.parent?t.id:null;}
function combo(n,seen=new Set()){const wrap=el('div','combo');if(seen.has(n.id)){wrap.append(makeCard(n));return wrap;}seen=new Set([...seen,n.id]);const chips=el('div','mini-pieces');/* Une attaque déclarée ne retire pas la pièce de la contribution : elle reste engagée
   tant que l'attaque n'est pas résolue. On la montre donc à sa place, signalée comme ciblée. */
for(const id of n.pieces||[]){const r=byId(id);if(r&&n.status!=='acquired'&&r.heldBy===n.id){const c=makeCard(r);c.classList.add('committed',n.type==='lock'?'for-lock':'for-key');const vise=attacking(r);if(vise){c.classList.add('under-attack');c.title='Encore engagée dans cette contribution, et ciblée par l’attaque '+vise.id+' — résultat non acquis.';}chips.append(c);};}for(let i=(n.pieces||[]).length;i<(n.type==='attack'?n.requiredCount||0:0);i++)chips.append(el('span','piece-chip slot','＋'));wrap.append(chips,makeCard(n));if(n.type==='attack'&&(n.defenders||[]).length){const defense=el('div','defensive-pieces');defense.append(el('span','defense-label','Défense de la cible'));for(const id of n.defenders){const r=byId(id);if(r&&r.heldBy===n.id){const c=makeCard(r);c.classList.add('committed','for-defense');defense.append(c);}}wrap.append(defense);}const attached=state.nodes.filter(x=>x.target===n.id&&visibleNode(x));if(attached.length){const a=el('div','attachments');attached.forEach(x=>a.append(combo(x,seen)));wrap.append(a);}return wrap;}
function renderState(n){const row=el('div',n.parent?'branch':'objective'),z=el('div','state-zone');z.append(makeCard(n));row.append(z);const lane=el('div','lane');lane.setAttribute('aria-label','Ressources posées à côté de '+n.title);const cards=el('div','cards');state.nodes.filter(x=>x.target===n.id&&['key','lock'].includes(x.type)&&visibleNode(x)).forEach(k=>cards.append(combo(k)));lane.append(cards);row.append(lane);return row;}
function slots(root){const area=el('div','branches'),existing=state.nodes.filter(n=>n.parent===root.id);(root.owner==='phoebe'?existing:[...existing].reverse()).forEach(n=>area.append(renderState(n)));const empty=el('div','empty-slots'),count=state.subgoalSlots?.[root.owner]??3;for(let i=existing.length;i<count;i++){const b=button('＋',()=>openDraft('subgoal',root.id),!own(root)||!paid(),'empty-subgoal');b.setAttribute('aria-label','Créer le sous-objectif '+(i+1)+' sur '+count);b.append(el('span','','Sous-objectif '+(i+1)));empty.append(b);}if(root.owner==='phoebe')area.append(empty);else area.prepend(empty);area.setAttribute('aria-label','Sous-objectifs : '+existing.length+' sur '+count);return area;}
function hand(camp){const h=el('div','hand');h.setAttribute('aria-label',camp.id==='phoebe'?'Votre main':'Main adverse');
 const groups=[['Disponibles',r=>['free','subject'].includes(r.availability)],['En attente',r=>!['free','subject','lost'].includes(r.availability)],['Perdues',r=>r.availability==='lost']];
 for(const [title,filter] of groups){const g=el('section','hand-group');g.append(el('h3','',title));const cards=el('div','cards');state.resources.filter(r=>r.owner===camp.id&&(!r.heldBy||retained(r))&&filter(r)).forEach(r=>{const w=el('div','combo');const c=makeCard(r);const vise=attacking(r);if(vise){c.classList.add('under-attack');c.title='Ciblée par l’attaque '+vise.id+' — résultat non acquis, la ressource est toujours à vous.';}w.append(c);cards.append(w);});g.append(cards);h.append(g);}
 if(camp.id==='phoebe')h.append(button('＋ Créer une ressource',()=>openDraft('resource'),busy||!['player','ai'].includes(state.phase),'create-resource'));return h;}
function fitCardTitles(){for(const card of document.querySelectorAll('.card')){const title=card.querySelector('.short'),front=card.querySelector('.front');let size=parseFloat(getComputedStyle(title).fontSize);while(size>6.5&&(title.scrollWidth>title.clientWidth+1||title.getBoundingClientRect().bottom>front.getBoundingClientRect().bottom-10)){size-=.5;title.style.setProperty('font-size',size+'px','important');}}}
function banner(camp){const b=el('div','banner');b.append(el('span','avatar',camp.icon),el('h2','',camp.name));const active=state.phase===(camp.id==='phoebe'?'player':'ai');b.append(el('strong','turn-label',active?(camp.id==='phoebe'?'● À VOUS DE JOUER':'● L’ADVERSAIRE JOUE'):'En attente'));if(active)b.classList.add('active-turn');return b;}
function readPages(title,text){$('detail').className='';const chunks=text.match(/[\s\S]{1,650}/g)||[text];let index=0;function page(){$('detail-title').textContent=title;$('detail-text').textContent=chunks[index];$('card-actions').replaceChildren(button('← Précédent',()=>{index--;page();},index===0),el('span','page-count',(index+1)+' / '+chunks.length),button('Suivant →',()=>{index++;page();},index===chunks.length-1));}page();$('detail').showModal();}
function contestVerdict(entry,parent){const d=illustratedDialog('calendar-parchment destiny-parchment contest-parchment'),form=el('form','contest-form'),reason=document.createElement('textarea');reason.rows=6;reason.maxLength=3000;reason.minLength=8;reason.required=true;reason.placeholder='Pourquoi contestes-tu ce verdict ?';form.append(reason,button('Enregistrer la contestation',null,false,'book-return'));form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('button');submit.disabled=true;try{const result=await request('/api/charmed/contest',{revision:state.revision,requestId:crypto.randomUUID(),arbitrationId:entry.id,reason:reason.value});notify(result.message,!!result.traceIncomplete);if(result.ok){d.close();parent?.close();await load();}}catch(error){notify(error.message,true);}finally{submit.disabled=false;}};d.append(el('h2','founders-heading','Contester ce verdict'),el('p','event-text','Explique pourquoi cette décision te paraît incorrecte. La contestation est gratuite et ne modifie pas automatiquement la partie.'),form,button('Annuler',()=>d.close(),false,'book-return'));d.showModal();reason.focus();}
function showDispatchPage(kind,entry,radio){const d=illustratedDialog('calendar-parchment '+(kind==='destiny'?'destiny-parchment':''));d.append(el('h2','founders-heading',kind==='destiny'?'L’Ange du destin':'Les Fondateurs'),el('p','book-kicker',radio?'Le message du matin':'Le message'),el('p','event-day','Jour '+entry.day),el('p','event-text',entry.text));if(kind==='destiny')d.append(button(entry.contested?'Verdict contesté':'Contester ce verdict',()=>contestVerdict(entry,d),!!entry.contested,'contest-verdict'));d.append(button('Revenir au plateau',()=>d.close(),false,'book-return'));d.showModal();}
function dispatches(container,entries,radio=false){container.replaceChildren();if(!entries.length){container.append(el('p','empty','Aucun message pour le moment.'));if(container.id==='arbitration'){const f=el('div','facts');f.id='facts';f.append(button('Faits établis',()=>readPages('Faits établis',state.facts.join('\n\n'))));container.append(f);}return;}let index=entries.length-1;function draw(){container.replaceChildren();const entry=entries[index],d=el('article','dispatch');d.append(el('time','',(radio?'MATIN DU JOUR ':'JOUR ')+entry.day),el('p','dispatch-excerpt',entry.text),button(radio?'Lire le bulletin':'Lire le message',()=>container.id==='opponent'?readPages('Message adverse · Jour '+entry.day,entry.text):showDispatchPage(container.id==='arbitration'?'destiny':'founders',entry,radio),false,'read-message'));if(container.id==='arbitration'){const f=el('div','facts');f.id='facts';f.append(button('Faits établis',()=>readPages('Faits établis',state.facts.join('\n\n'))));d.append(f);}container.append(d);if(entries.length>1){const nav=el('div','panel-navigation');nav.append(button('←',()=>{index--;draw();},index===0),el('span','',(index+1)+' / '+entries.length),button('→',()=>{index++;draw();},index===entries.length-1));container.append(nav);}}draw();}
function render(){const scrollPositions=new Map([...document.querySelectorAll('.territory')].map(t=>[t.className,{top:t.querySelector('.camp-play').scrollTop,left:t.querySelector('.camp-play').scrollLeft}]));if(chosen&&!free(byId(chosen)||{}))chosen=null;$('game-title').textContent=state.title;document.title='Charmed — '+state.title;$('day').textContent='Jour '+state.day+' / '+state.finalDay;$('phase').textContent=({player:'● À VOUS DE JOUER',ai:'● L’ADVERSAIRE JOUE',morning:'LES FONDATEURS · AUCUN JOUEUR NE JOUE',finished:'PARTIE TERMINÉE'})[state.phase];const board=$('board');board.replaceChildren();for(const camp of [...state.camps].reverse()){const isPlayer=camp.id==='phoebe',territory=el('section','territory '+(isPlayer?'player':'enemy')),root=state.nodes.find(n=>n.type==='state'&&!n.parent&&n.owner===camp.id),play=el('div','camp-play'),battle=el('div','battle');if(isPlayer)battle.append(renderState(root),slots(root));else battle.append(slots(root),renderState(root));play.append(battle);const attacks=el('section','attack-zone');attacks.append(el('h3','','Zone d’attaque'));const ongoing=state.nodes.filter(n=>n.type==='attack'&&n.owner===camp.id&&!['removed'].includes(n.status));if(!ongoing.length){attacks.classList.add('vacant');const add=button('＋',()=>{ $('detail').className='';$('detail-title').textContent='Choisir la cible de l’attaque';$('detail-text').textContent='Sélectionnez une ressource adverse.';$('card-actions').replaceChildren(...state.resources.filter(r=>r.owner!==camp.id&&r.availability!=='lost').map(r=>button(r.title,()=>openDraft('attack',r.id))));$('detail').showModal();},!isPlayer||!paid()||!state.resources.some(free),'attack-add');add.setAttribute('aria-label','Déclarer une attaque');attacks.append(add);}for(const n of ongoing){const entry=el('div','attack-entry');const victim=byId(n.target);if(victim&&attacking(victim)?.id===n.id){const targetCard=makeCard(victim);targetCard.classList.add('attack-victim');entry.append(targetCard);}entry.append(el('p','attack-target','Cible : '+(byId(n.target)?.title||n.target)),combo(n));attacks.append(entry);}play.prepend(attacks);const body=el('div','territory-body');body.append(play,hand(camp));const side=el('aside','camp-side');if(!isPlayer){side.append(el('h2','','🎭 Le coup adverse'));const messages=el('div','');messages.id='opponent';side.append(messages);}if(isPlayer)territory.append(body,banner(camp));else {const head=banner(camp);head.append(side);territory.append(head,body);}board.append(territory);}
 renderCalendar();dispatches($('radio'),state.radio,true);dispatches($('arbitration'),state.arbitration);dispatches($('opponent'),state.opponent.slice(-1));$('budget').textContent=state.result?(state.result.winner==='phoebe'?'Victoire !':state.result.winner?'Défaite':'Fin sans vainqueur'):state.phase!=='player'?'Votre passage est terminé':state.spent.phoebe?'Coup joué · questions et réponses encore possibles':'Votre coup du jour est disponible';$('hint').replaceChildren(el('span','',chosen?'Ressource choisie : '+byId(chosen).title+' · cliquez sur sa cible.':'Glissez une ressource sur une cible ; cliquez sur une carte pour agir ou poser une question.'));if(chosen)$('hint').append(button('Annuler la sélection',()=>{chosen=null;render();}));requestAnimationFrame(()=>{fitCardTitles();for(const t of document.querySelectorAll('.territory')){const area=t.querySelector('.camp-play'),previous=scrollPositions.get(t.className);if(previous){area.scrollTop=previous.top;area.scrollLeft=previous.left;}else{const root=t.querySelector('.objective');area.scrollTop=Math.max(0,root.getBoundingClientRect().bottom-area.getBoundingClientRect().bottom+12);}}});$('turn-copy').replaceChildren(el('strong','', $('phase').textContent));setBusy(busy);}
function renderCalendar(){const c=$('calendar');const entries=(state.calendar||[]).map(e=>({day:e.morning,title:e.title,text:[e.title,e.condition?'Si : '+e.condition:'',e.effect,...state.camps.map(camp=>camp.name+' : '+(e.impacts?.[camp.id]||'Selon la situation.'))].filter(Boolean).join('\n\n')}));for(const n of state.nodes.filter(n=>n.type==='attack'&&n.dueDay&&state.day>=n.revealDay&&!['removed'].includes(n.status)))entries.push({day:n.dueDay,title:'Attaque · '+(byId(n.target)?.title||n.title),text:cardText(n)});let selected=state.day,eventIndex=0;
 function draw(){c.replaceChildren();const grid=el('div','calendar-overview');grid.setAttribute('aria-label','Vue globale des jours et événements');for(let day=1;day<=state.finalDay;day++){const events=entries.filter(e=>e.day===day),cell=button('',()=>{selected=day;eventIndex=0;draw();showCalendarEvent(day,events);},false,'calendar-day'+(events.length?' has-event':'')+(day===state.day?' today':'')+(day===selected?' selected':'')+(day<state.day?' past':''));cell.setAttribute('aria-label','Jour '+day+(day===state.day?', aujourd’hui':'')+(events.length?', '+events.length+' événement(s) annoncé(s)':', aucun événement annoncé'));cell.setAttribute('aria-pressed',String(day===selected));cell.append(el('span','','J'+day),el('span','day-dot',events.length?'•':''));grid.append(cell);}c.append(grid,el('p','calendar-legend','● Événement annoncé · cadre : aujourd’hui'));const detail=el('div','calendar-selected');detail.append(el('h3','','Jour '+selected+(selected===state.day?' · Aujourd’hui':'')));const events=entries.filter(e=>e.day===selected);if(!events.length)detail.append(el('p','no-event','Aucun événement annoncé.'));else{const e=events[eventIndex];detail.append(button(e.title,()=>showCalendarEvent(selected,events,eventIndex),false,'selected-event'));if(events.length>1){const nav=el('div','panel-navigation');nav.append(button('←',()=>{eventIndex--;draw();},eventIndex===0),el('span','',(eventIndex+1)+' / '+events.length+' événements'),button('→',()=>{eventIndex++;draw();},eventIndex===events.length-1));detail.append(nav);}}c.append(detail);}draw();}
function setBusy(value){busy=value;if(!state)return;const kind=draft?.kind,isFree=['question','answer','resource'].includes(kind);$('submit').disabled=busy||!(state.phase==='player'||(kind==='resource'&&state.phase==='ai'))||(!isFree&&state.spent.phoebe);$('end').disabled=busy||state.phase!=='player';$('resume').hidden=!['ai','morning'].includes(state.phase);$('resume').disabled=busy;$('close-composer').disabled=busy;document.body.classList.toggle('locked-ui',state.phase!=='player');}
async function request(url,payload){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error||'Opération impossible.');return b;}
async function load(){const r=await fetch('/api/charmed');const b=await r.json();if(!r.ok)throw new Error(b.error);state=b;render();}
async function advance(){while(['ai','morning'].includes(state.phase)){notify(state.phase==='ai'?'L’adversaire prépare son passage…':'Les Fondateurs prépare le matin…');setBusy(true);state=await request('/api/charmed/advance',{revision:state.revision,requestId:crypto.randomUUID()});render();}notify('');}
async function run(action){if(busy)return;setBusy(true);notify(action.type==='end'?'Votre passage se termine…':'L’Ange du destin examine votre proposition…');try{const before=state.arbitration.length;state=await request('/api/charmed/action',{revision:state.revision,requestId:crypto.randomUUID(),action});chosen=null;if(action.type==='end'){$('composer').close();draft=null;render();notify('');await advance();}else{$('composer-title').textContent=action.type==='answer'?'Réponse enregistrée · examen ce soir':'Proposition enregistrée';$('composer-context').textContent='Retour sur votre proposition';$('action-form').hidden=true;const receipt=$('receipt');receipt.hidden=false;receipt.replaceChildren(...state.arbitration.slice(before).map(a=>el('p','',a.text)));if(!receipt.children.length)receipt.append(el('p','',action.type==='question'?'Question posée. L’action ciblée est suspendue en attendant une réponse valide.':'Proposition enregistrée.'));if(!$('composer').open)$('composer').showModal();draft=null;render();notify('');}}catch(e){notify(e.message,true);try{await load();}catch{}}finally{setBusy(false);render();}}
 $('effect-kind').onchange=()=>writingHelp($('effect-kind').value);
 $('action-form').onsubmit=e=>{e.preventDefault();if(!draft)return;const k=['key','lock'].includes(draft.kind)?$('effect-kind').value:draft.kind;run({type:['place','defend','question','answer'].includes(k)?k:'propose',kind:k,target:draft.target,resource:draft.resource,text:$('proposal').value});};$('end').onclick=()=>run({type:'end'});$('resume').onclick=async()=>{try{setBusy(true);await advance();}catch(e){notify(e.message,true);try{await load();}catch{}}finally{setBusy(false);render();}};$('close-detail').onclick=()=>$('detail').close();$('close-composer').onclick=()=>$('composer').close();$('composer').addEventListener('cancel',e=>{if(busy)e.preventDefault();});const rulesButton=button('Règles du jeu',async()=>{try{const r=await fetch('/api/charmed/rules');if(!r.ok)throw new Error('Chargement des règles impossible');const data=await r.json();const d=illustratedDialog('calendar-parchment rules-parchment');d.append(el('h2','','Règles du jeu'));for(const block of data.text.split(/\r?\n\r?\n/)){if(!block.trim())continue;const title=block.trim().match(/^#{1,3} (.*)$/);d.append(el(title?'h3':'p',title?'rules-heading':'event-text',title?title[1]:block.replace(/\*\*/g,'')));}d.append(button('Revenir au plateau',()=>d.close(),false,'book-return'));d.showModal();}catch(e){notify(e.message,true);}},false,'rules-access');document.querySelector('.turn-panel').append(rulesButton);load().catch(e=>notify('Impossible de charger : '+e.message,true));
})();
