"use strict";
const fs=require('fs'),path=require('path'),{call}=require('../serveur/charmed/intelligence'),scenario=require('../serveur/charmed/scenario'),{evaluate}=require('../serveur/charmed/gameplay');
const str={type:'string'},obj=p=>({type:'object',properties:p,required:Object.keys(p),additionalProperties:false});
const schema=obj({routes:{type:'array',items:obj({camp:{type:'string',enum:['phoebe','commanditaire']},title:str,sufficiency:str,branches:{type:'array',items:obj({condition:str,contribution:str,attack:{type:'boolean'},resources:{type:'array',items:str}})}})}});
(async()=>{
 const result=await call(JSON.stringify({role:'Conception privée du gameplay avant partie',scenario:{goals:scenario.goals,resources:scenario.resources,reference:scenario.privateFacts},instruction:'Propose exactement deux chemins alternatifs plausibles par camp, composés de sous-objectifs pertinents suffisants ensemble pour son objectif initial, sans opposition. Ces chemins servent uniquement à estimer le nombre de places ; leurs noms ne seront pas imposés ni révélés. Ne choisis pas arbitrairement trois branches : découpe selon la causalité réelle. Chaque branche consomme un coup de création ; si elle exige une attaque, attack=true et ajoute EN PLUS le coup de déclaration, puis un coup par ressource et se résout le matin suivant. Les ressources se libèrent lorsque cette branche est vraie. On commence J1 ; le dernier résultat doit être au plus tard au matin J12. Au moins une ressource existante par branche ; pas d’objets ni pouvoirs inventés. Chaque sous-objectif peut comprendre plusieurs effets cohérents de ses moyens, pas de victoire par sa seule création. Pour le meurtrier, une attaque mortelle doit rester une véritable action à préparer, pas une convocation qui tue automatiquement : ses étapes et moyens doivent justifier causalement les conditions finales ; le témoin ne donne aucune action gratuite en partie. Pour Phoebe, une protection doit effectivement empêcher le meurtre à échéance, pas seulement retarder la rencontre.'}),schema);
 const capacities=evaluate(result,scenario.resources,scenario.finalDay);
 const output={schema:'charmed-gameplay-capacity-1',capacities,method:'Maximum des besoins de places de deux chemins causaux alternatifs par camp, avec calendrier séquentiel contrôlé. Estimation narrative sans opposition, pas une preuve d’équilibrage.',...result};
 fs.writeFileSync(path.join(__dirname,'../docs/parties/avant-la-vision-gameplay.json'),JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify({capacities,completionMornings:result.routes.map(r=>r.completionMorning)}));
})().catch(e=>{console.error(e.message);process.exitCode=1;});
