"use strict";
const str={type:'string'},bool={type:'boolean'},integer={type:'integer'},strings={type:'array',items:str};
const obj=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const audit=obj({status:{type:'string',enum:['ordinary','verified','unverified']},facts:strings,reason:str});
const means={accepted:bool,reason:str,sufficient:bool,missing:integer,delay:integer,situationChanged:bool,changeReason:str,dependsOn:strings,canon:audit};
const planSchema=obj({...means,title:str,effect:str,locations:strings,requiredCount:integer,resource:obj({title:str,description:str,category:str,icon:str,canonicalId:str,unique:bool}),costs:strings});
const placementSchema=obj(means),answerSchema=obj(means);
const outcomeSchema=obj({id:str,success:bool,reason:str,established:str,usedResources:strings,losses:strings,consume:strings,recovery:{type:'array',items:obj({id:str,days:integer})},maintainers:strings,transfers:{type:'array',items:obj({id:str,owner:str})},controlChanges:{type:'array',items:obj({id:str,owner:str})},defenderBenefit:str});
const resolutionSchema=obj({outcomes:{type:'array',items:outcomeSchema},states:{type:'array',items:obj({id:str,value:bool,reason:str,supports:strings})},facts:strings,fallenLocks:strings,victory:{type:'array',items:obj({root:str,allConditions:bool,secure:bool,reason:str})}});
resolutionSchema.properties.canon=audit;resolutionSchema.required.push('canon');
module.exports={planSchema,placementSchema,answerSchema,resolutionSchema,obj,bool,str};
