'use strict';
const specs=[
 ['phoebe','Phoebe Halliwell','personnage','Prémonitions et enquête. Saison 7 après Scry Hard : pas de lévitation ni d’empathie disponibles. Une vision ne se commande pas à volonté. Présente au manoir.'],
 ['piper','Piper Halliwell','personnage','Fige et provoque des explosions moléculaires dans les limites établies de ses pouvoirs. Une explosion ne détruit pas automatiquement un démon puissant. Présente dans la cuisine.'],
 ['paige','Paige Matthews','personnage','Éclipse et télékinésie orbitale liées à Paige, avec présence, cible et destination accessibles. Pas de guérison acquise à cette période. Présente au grenier.'],
 ['livre','Livre des Ombres','objet','Livre unique de la lignée, présent au grenier. Sa possession ne révèle pas son contenu. Sa consultation ne détruit pas le livre physique et ne réalise pas le sort.'],
 ['grenier','Grenier','lieu','Pièce tenue par les sœurs. Accès au Livre et espace de préparation ; aucune protection automatique contre toute intrusion.'],
 ['sous-sol','Sous-sol','lieu','Pièce actuellement tenue par les sœurs, porte intérieure fermée. Le Nexus est un enjeu du lieu, pas un objet transportable ni une ressource déjà maîtrisée.'],
 ['cristaux','Cristaux','objet','Ensemble de cristaux de confinement à disposer et à utiliser selon les règles canoniques. Aucun piège actif au départ ; ne localise pas un démon.'],
 ['materiel','Matériel de potion','objet','Mortier, fioles et ustensiles. Ce matériel ne remplace ni les ingrédients spécifiques ni une formule établie.'],
 ['zankou','Zankou','personnage','Démon stratège hostile aux sœurs. Aucune prémonition, aucun pouvoir des sœurs volé ni maîtrise du Nexus au départ. Coordonne ses agents depuis son repaire.'],
 ['guetteur','Guetteur','personnage','Démon subalterne original affecté à l’observation depuis la rue. Peut observer une entrée visible, suivre matériellement, transmettre une information ; aucun pouvoir supplémentaire acquis par son nom.'],
 ['eclaireur','Éclaireur','personnage','Agent démoniaque original présent dans le repaire. Peut se déplacer, reconnaître un accès matériel et agir physiquement. Pas de passe-muraille ou d’invisibilité accordés gratuitement.'],
 ['repaire','Repaire','lieu','Lieu tenu par Zankou, distinct du manoir ; abrite les préparatifs. Aucune voie directe magique vers le sous-sol.'],
 ['message','Message anonyme','objet','Feuille vierge et enveloppe pouvant porter un message. Son texte et son acheminement doivent être proposés ; personne ne croit ni ne suit automatiquement une convocation.'],
 ['outils','Outils de passage','objet','Outils matériels pour une ouverture physique accessible. Ne traversent ni protections magiques ni murs instantanément.']
];
const resources=specs.map(([id,title,category,description],i)=>({id,title,category,description,icon:category==='personnage'?'✦':category==='lieu'?'⌂':'📦',owner:i<8?'phoebe':'commanditaire',availableDay:1,heldBy:null,lost:false,consumed:false,unique:category==='personnage'||id==='livre',preparation:false}));
const branch=(condition,contribution,resources)=>({condition,contribution,resources,attack:false});
const routes=[
 {camp:'phoebe',title:'Défense distribuée',sufficiency:'Reconnaissance puis protections distinctes ; les moyens des sœurs sont réutilisables après validation de chaque branche. Le succès suppose de défaire les intrusions concrètes, pas une invulnérabilité déclarée.',branches:[branch('Les accès utilisés par les assaillants sont identifiés.','Observation et reconnaissance.',['phoebe','grenier']),branch('Le passage vers le sous-sol est effectivement protégé.','Dispositif situé, cohérent et préparé.',['piper','cristaux']),branch('La liaison entre les pièces tenues est assurée.','Accès et intervention effective de Paige.',['paige','sous-sol'])]},
 {camp:'phoebe',title:'Interrompre le siège',sufficiency:'Trouver puis contrarier les moyens opérationnels adverses tout en gardant le contrôle du sous-sol. Ne requiert pas de tuer Zankou avec une potion inventée.',branches:[branch('Les relais du siège sont identifiés.','Enquête auprès des accès observables.',['phoebe','grenier']),branch('L’intervention contre un relais est préparée sans abandon du sous-sol.','Coordination des deux sœurs disponibles.',['piper','paige'])]},
 {camp:'commanditaire',title:'Diversion et intrusion',sufficiency:'Une diversion crédible doit produire un départ réel, puis un passage doit être ouvert et tenu contre les sœurs. Aucun courrier ne contraint automatiquement une sœur.',branches:[branch('Une diversion crédible est parvenue aux sœurs.','Observer puis transmettre une information ciblée.',['guetteur','message']),branch('Un accès matériel au manoir est praticable pour un agent.','Reconnaître puis ouvrir un accès.',['eclaireur','outils']),branch('Le sous-sol est occupé et défendu par le camp adverse.','Intervention située de Zankou après libération des moyens précédents.',['zankou','repaire'])]},
 {camp:'commanditaire',title:'Pression sur les accès',sufficiency:'Observer les sorties, mettre une pression concrète sur les accès puis tenir le sous-sol. Une attaque doit respecter déclaration, révélation et engagements.',branches:[branch('Les mouvements utiles des sœurs sont connus.','Observation limitée depuis la rue.',['guetteur']),branch('Un moyen de pression contre un accès est en place.','Action physique située.',['eclaireur','outils']),branch('Le camp tient le sous-sol sans intervention possible immédiate.','Occupation et coordination des moyens survivants.',['zankou','repaire'])]}
];
const event=(morning,title,effect,balance,grants)=>({id:'siege-j'+morning,morning,title,effect,public:true,balance,impacts:{phoebe:effect,commanditaire:effect},...(grants?{grants}:{})});
module.exports={id:'manoir-assiege',title:'Le manoir assiégé',period:'Saison 7, après Scry Hard, avant la fin de saison. Aventure inédite.',canonPeriod:{season:7,episode:17,moment:'after'},finalDay:14,resources,
 subgoalSlots:require('./gameplay').evaluate({routes},resources,14),
 camps:[{id:'phoebe',name:'Les sœurs Halliwell',icon:'✦'},{id:'commanditaire',name:'Zankou',icon:'◆'}],
 opponentRole:'Zankou, démon stratège. Patient, manipulateur, attentif aux liens entre les sœurs. Aucun pouvoir volé au départ.',
 goals:[
 {id:'root-phoebe',owner:'phoebe',shortTitle:'Le manoir préservé',initialValue:true,title:'Le manoir demeure sous le contrôle des sœurs : Piper, Phoebe et Paige sont vivantes, le Livre des Ombres reste sous leur garde et aucun agent de Zankou ne contrôle le sous-sol ni le Nexus jusqu’au matin du jour 14.'},
 {id:'root-commanditaire',owner:'commanditaire',shortTitle:'Le sous-sol conquis',initialValue:false,title:'Zankou contrôle durablement le sous-sol du manoir, les sœurs ne peuvent plus y intervenir avant le matin du jour 14 et un accès effectif au lieu du Nexus est établi pour son camp.'}],
 initialFacts:['Piper, Phoebe et Paige sont vivantes et présentes au manoir.','Le Livre des Ombres est dans le grenier et sous la garde des sœurs.','Le sous-sol et ses accès intérieurs sont tenus par les sœurs ; aucun agent adverse ne s’y trouve.','Zankou ne contrôle pas le Nexus et ne détient aucun pouvoir volé aux sœurs.'],
 opening:'Le manoir est encore à vous. Dans la nuit, une silhouette a observé la maison depuis le trottoir ; à l’aube, Piper découvre des traces près de l’accès extérieur. Paige retrouve le grenier intact et Phoebe remarque une enveloppe glissée sous la porte : « Vous ne pourrez pas garder chaque pièce à la fois. » Le Livre est à sa place. Le sous-sol est fermé. Le siège commence. Vous contrôlez les trois sœurs ; votre état initial est VRAI et doit être maintenu jusqu’au matin du jour 14. Trois emplacements de sous-états sont disponibles, sans solutions imposées.',
 calendar:[event(3,'Avis de travaux','Publication d’un avis de travaux de voirie ; chaque camp reçoit un exemplaire à consulter.','occasion commune',[{id:'avis',title:'Avis de travaux',icon:'📄',category:'objet',description:'Document public non encore consulté : horaires et périmètre des travaux du quartier, pas le plan intérieur du manoir.'}]),event(5,'Travaux dans la rue','De J5 à J6, des travaux bruyants ont lieu dans la rue. Ils changent les conditions d’écoute et de déplacement extérieur, sans ouvrir le manoir ni neutraliser la magie.','contrainte commune'),event(7,'Fin des travaux','La rue retrouve son accès ordinaire. Les conséquences déjà établies des actions restent à évaluer.','occasion commune'),event(10,'Coupure électrique','Une maintenance coupe l’électricité du quartier pendant J10. Éclairage et appareils électriques sont concernés ; les pouvoirs magiques ne disparaissent pas.','contrainte commune'),event(11,'Retour du courant','Le courant revient au matin ; aucun dispositif détruit ne se répare automatiquement.','occasion commune'),event(14,'Fin de l’épreuve','Constat des conditions initiales et des menaces encore réalisables. Aucun camp ne gagne sur la seule annonce du calendrier.','échéance commune')],
 campKnowledge:{commanditaire:['Je suis Zankou et j’organise un nouveau siège, sans lire les plans privés du joueur.','Les sœurs disposent du manoir et du Livre au départ. Je convoite le sous-sol et le Nexus, mais je ne les contrôle pas.','Mon guetteur est dans la rue, mon éclaireur au repaire. Je connais leurs moyens décrits sur leurs cartes.','Une sœur au manoir peut contrarier ma tentative ; les écarter exige des faits. L’accès au sous-sol n’est pas l’absorption du Nexus.','Je ne dispose ni de prémonitions ni de pouvoirs volés aux sœurs. Mes subalternes originaux ne possèdent aucun pouvoir non établi.']},
 privateFacts:{documents:{'Avis de travaux':'Travaux J5 et J6, de 8 h à 18 h, sur la chaussée devant le pâté de maisons. Le trottoir côté manoir reste piéton. Bruit de chantier intermittent. Aucun accès à une propriété privée autorisé.'},routes,inventions:['Nouveau siège et calendrier civils fictifs.','Deux subalternes originaux, capacités définies sur leurs cartes.','Léo et les enfants sont à l’abri hors du manoir dans cette ouverture ; ils ne sont ni captifs ni ressources initiales.']},
 doctrine:'Conserver les règles actées. Histoire nouvelle, pas reproduction de Scry Hard. Contrôle matériel du sous-sol, accès au Nexus, invocation et maîtrise sont distincts. La victoire adverse exige le contrôle durable du lieu, pas une absorption du Nexus fictivement automatique. La protection du joueur commence vraie et doit être maintenue, sans victoire immédiate J1. Ne jamais créer des conditions supplémentaires au libellé des objectifs. Trois sous-états au maximum par camp, branches libres, voie directe possible. Ne pas annoncer les ressources manquantes, seulement leur nombre. Documents : contenu fixe dans privateFacts.documents, transmis uniquement après consultation effective. Léo est mortel à cette période ; Paige ne guérit pas encore. Pouvoirs de Phoebe selon chronologie, pas empathie ni lévitation rétablies gratuitement. Aucune potion générique ne tue automatiquement Zankou. Les surprises sont des conséquences cohérentes de faits sur le plateau, jamais une règle magique inventée.'
};
