'use strict';
const specs=[
 ['prue','Prue Halliwell','personnage','Télékinésie et projection astrale. Une seule personne : sa projection ne crée pas une seconde ressource.'],
 ['piper','Piper Halliwell','personnage','Fige les personnes et objets dans la portée de son pouvoir. À cette période, elle ne possède pas encore le pouvoir explosif.'],
 ['phoebe','Phoebe Halliwell','personnage','Prémonitions par contact pertinent, lévitation et arts martiaux.'],
 ['leo','Leo Wyatt','personnage','Être de lumière : éclipse par orbes, transport accompagné et guérison dans les limites de sa fonction. Le poison des Êtres des ténèbres menace sa vie.'],
 ['natalie','Natalie','personnage','Être de lumière expérimentée : éclipse par orbes, transport accompagné et protection de ses protégés. Rigoureuse, vulnérable au poison des Êtres des ténèbres.'],
 ['livre','Livre des Ombres','objet','Livre unique des Halliwell. Consultation des connaissances et préparation de formules ; aucun sort exécuté automatiquement.'],
 ['athame','Athamé abandonné','objet','Arme abandonnée par Eames lors de son dernier affrontement. Porte une trace de son passage.'],
 ['pendule','Pendule et carte','objet','Cristal de recherche et carte de San Francisco pour une localisation magique avec un lien pertinent.'],
 ['eames','Eames','personnage','Sorcier maléfique : déplacement par clignement, déviation, duplication temporaire, transformation en objet et boules de feu. Ne possède pas encore l’éclipse des guides. Un double ne devient pas une carte indépendante.'],
 ['arbalete','Arbalète des ténèbres','objet','Arbalète utilisable avec un carreau. Ne produit pas de munitions.'],
 ['carreau-1','Carreau empoisonné 1','objet','Projectile empoisonné d’Être des ténèbres, mortel pour un Être de lumière s’il est effectivement atteint et succombe à la blessure.'],
 ['carreau-2','Carreau empoisonné 2','objet','Second projectile empoisonné d’Être des ténèbres. Une munition distincte, avec les mêmes propriétés.'],
 ['adrien','Adrien Voss','personnage','Guetteur humain payé par Eames. Observation, filature et transmission ordinaires.']
];
const resources=specs.map(([id,title,category,description],i)=>({id,title,category,description,icon:category==='personnage'?'✦':'📦',owner:i<8?'phoebe':'commanditaire',availableDay:1,heldBy:null,lost:false,consumed:false,unique:category==='personnage'||id==='livre',canonicalId:id,preparation:false}));
module.exports={
 id:'la-chasse-aux-guides',title:'La Chasse aux guides',period:'Saison 3 : aventure alternative au moment de la menace d’Eames. Natalie est vivante ; son destin dépend de la partie.',canonPeriod:{season:3,episode:11,moment:'after'},finalDay:16,
 resources,subgoalSlots:{phoebe:3,commanditaire:3},
 canonSources:[{id:'guides:transcript0311',type:'transcription_non_officielle',url:'https://www.springfieldspringfield.co.uk/view_episode_scripts.php?episode=s03e11&tv-show=charmed'},{id:'guides:recap0311',type:'recit_secondaire',url:'https://90sflashback.wordpress.com/2025/07/12/charmed-3-11-blinded-by-the-whitelighter-winging-it/'}],
 canonFacts:[
  {id:'guides:etres-de-lumiere',season:3,episode:11,status:'verified',entities:['leo','natalie'],claim:'Leo et Natalie sont des Êtres de lumière capables de déplacement par orbes ; le transport accompagné est possible. Leo soigne dans les limites de sa fonction. Le poison des Êtres des ténèbres constitue une menace mortelle, sans guérison ordinaire garantie.',sources:['guides:transcript0311','guides:recap0311'],limits:['Référence documentaire textuelle et secondaire, pas contrôle audiovisuel. Présence, destination accessible et engagement à examiner ; pas de protection absolue.']},
  {id:'guides:eames-arsenal',season:3,episode:11,status:'verified',entities:['eames'],claim:'Eames combine des pouvoirs acquis : clignement, déviation, duplication temporaire, transformation en objet et boules de feu. Il emploie une arbalète et des projectiles empoisonnés pris à un Être des ténèbres pour menacer les guides.',sources:['guides:transcript0311','guides:recap0311'],limits:['Dans cette aventure, ces moyens sont acquis au départ ; éclipse des guides non acquise. Double temporaire non autonome, arme distincte du pouvoir, munitions finies.']}
 ],
 camps:[{id:'phoebe',name:'Les Halliwell et leurs guides',icon:'✦'},{id:'commanditaire',name:'Eames',icon:'◆'}],
 opponentRole:'Eames, sorcier maléfique rusé qui chasse les Êtres de lumière. Il observe, prépare ses attaques et exploite les occasions ; ses pouvoirs sont ceux de sa carte.',
 goals:[
  {id:'root-phoebe',owner:'phoebe',shortTitle:'Les guides sauvés',initialValue:false,title:'Leo et Natalie sont vivants et libres, et Eames est durablement hors d’état de les tuer : il est neutralisé, ou son camp est privé de ses deux carreaux empoisonnés sans autre moyen létal établi contre les guides.'},
  {id:'root-commanditaire',owner:'commanditaire',shortTitle:'Un guide abattu',initialValue:false,title:'Eames a tué Leo ou Natalie et reste vivant et libre.'}
 ],
 initialFacts:[
  'Au matin J1, Prue, Piper, Phoebe, Leo et Natalie sont vivants, libres et réunis au manoir. Aucun guide n’est blessé ni empoisonné.',
  'Eames a échoué dans une attaque précédente et abandonné son athamé. Natalie l’a rapporté au manoir et a identifié son agresseur.',
  'Natalie a vu une arbalète et deux carreaux empoisonnés en possession d’Eames. Les deux projectiles sont encore intacts.',
  'Eames a été aperçu hier près d’un hangar du quartier industriel. Cette observation ne donne pas sa position actuelle.',
  'Aucun piège, sort de protection ou lien de localisation n’est déjà actif. Eames ne possède pas le pouvoir d’éclipse des Êtres de lumière.',
  'Les pouvoirs et équipements inscrits sur les cartes sont acquis au départ de cette aventure alternative. Les événements ultérieurs de l’épisode ne sont pas prédéterminés.'
 ],
 opening:'Natalie dépose un athamé sur la table du manoir. « Eames. Il avait une arbalète d’Être des ténèbres. Deux carreaux. » Leo s’approche, mais elle retient son bras : « Il voulait que je te conduise jusqu’à lui. » Prue ferme les rideaux. Dehors, la rue paraît calme. Vous avez quinze journées pour mettre fin à cette chasse. Vous contrôlez Prue, Piper, Phoebe, Leo et Natalie : tous sont des ressources disponibles dès maintenant. Votre objectif est de sauver les deux guides et de neutraliser la menace d’Eames. Créez librement une clé, un sous-état ou une attaque avec les commandes du plateau. Aucun décès ni chemin de résolution n’est imposé.',
 calendar:[
  {id:'guides-j3',morning:3,title:'Rappel des guides',effect:'Les Fondateurs rappellent les autres Êtres de lumière. Leo et Natalie restent auprès des Halliwell et demeurent jouables. Aucun renfort supplémentaire n’arrive automatiquement.',public:true,balance:'contexte commun',impacts:{phoebe:'Leo et Natalie restent disponibles selon leurs engagements.',commanditaire:'Aucun autre guide n’est une cible automatiquement disponible.'}},
  {id:'guides-j16',morning:16,title:'Fin de la chasse',effect:'Dernier constat des objectifs et des menaces établies. Aucun sauvetage, décès ou succès automatique.',public:true,balance:'échéance commune',impacts:{phoebe:'Constat final.',commanditaire:'Constat final.'}}
 ],
 campKnowledge:{commanditaire:['Je commence dans un hangar du quartier industriel, avec mon arbalète, mes deux carreaux et Adrien.','Natalie a échappé à ma précédente attaque ; elle a emporté mon athamé. Les Halliwell peuvent apprendre mon identité et rechercher ma trace.','Leo et Natalie sont les guides des Halliwell dans cette aventure. Je ne connais pas leurs projets ni leurs futures positions.','Mon objectif est de tuer au moins un guide et de rester vivant et libre. Je dois déclarer, préparer et résoudre mes attaques selon les règles.']},
 privateFacts:{documents:{},inventions:['Aventure alternative : Natalie vivante, athamé récupéré, deux munitions comptées, Adrien humain et calendrier.'],positionsInitiales:{eames:'hangar du quartier industriel',adrien:'hangar du quartier industriel'}},
 doctrine:'Aventure originale de saison 3. Le repère S03E11 sert aux capacités, jamais à imposer les événements : Natalie et Eames commencent vivants. Leo et Natalie sont de vraies ressources du joueur, engageables en clés, verrous, attaques ou défenses comme les sœurs. Aucun rappel ne les retire. Respecter la présence et les engagements ; pas de défense accomplie automatiquement ailleurs. Piper ne provoque pas d’explosions, Phoebe n’a pas d’empathie, Paige est absente. Le Pouvoir des Trois repose ici sur Prue, Piper et Phoebe. Les capacités initiales explicites des cartes font partie de la situation établie ; ne pas exiger de rejouer leur acquisition. Une création de formule cohérente peut être arbitrée sans reprendre les mots de l’épisode. Aucun succès magique automatique. Mort, blessure et empoisonnement sont distincts : la résolution de chaque attaque examine son effet annoncé et ses défenses ; aucun compteur de poison supplémentaire ni décès de calendrier. Une guérison ordinaire ne neutralise pas automatiquement le poison des Êtres des ténèbres. Les projectiles sont comptés individuellement ; ne pas en recréer gratuitement. Aucun pouvoir volé n’est acquis gratuitement après une attaque. Les doubles ne sont pas des acteurs indépendants et les transformations ne créent pas une ressource matérielle supplémentaire. Chaque objectif doit être évalué selon son libellé uniquement ; sauver les guides ne nécessite pas de voler un pouvoir ou de suivre une recette. Une attaque sur une ressource ne suffit pas à établir des conditions étrangères à son résultat réel. Les cartes et leur identité étant visibles, ne pas inventer après coup qu’une carte ordinaire était Eames déguisé. Pas de victoire seulement sur une promesse de protection.'
};
