"use strict";
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const clone=value=>value===undefined?null:JSON.parse(JSON.stringify(value));
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');
function arbitrationId(entry,index){return entry?.id||'arb-'+sha(JSON.stringify({day:entry?.day??null,text:entry?.text??'',index})).slice(0,20);}
class ArbitrationJournal{
 constructor({root,stateFile,scenarioId}){this.root=path.resolve(root);this.stateFile=path.resolve(stateFile);this.scenarioId=scenarioId||'unknown';this.warning=null;this.contested=new Set();this.instanceId=this.identity();this.file=path.join(this.root,'events',this.instanceId+'.jsonl');this.readIndex();}
 identity(){try{fs.mkdirSync(this.root,{recursive:true});const file=path.join(this.root,'instances.json'),key=sha(this.stateFile+'\n'+this.scenarioId);let registry={version:1,instances:{}};if(fs.existsSync(file))registry=JSON.parse(fs.readFileSync(file,'utf8'));registry.instances??={};registry.instances[key]??={gameInstanceId:crypto.randomUUID(),stateFile:this.stateFile,scenarioId:this.scenarioId,createdAt:new Date().toISOString()};const tmp=file+'.tmp-'+process.pid;fs.writeFileSync(tmp,JSON.stringify(registry,null,2));fs.renameSync(tmp,file);return registry.instances[key].gameInstanceId;}catch(e){this.warning='Identité du journal indisponible : '+e.message;return 'unavailable-'+sha(this.stateFile).slice(0,16);}}
 readIndex(){try{if(!fs.existsSync(this.file))return;for(const line of fs.readFileSync(this.file,'utf8').split(/\r?\n/)){if(!line)continue;const e=JSON.parse(line);if(e.type==='verdict.contested'&&e.arbitrationId)this.contested.add(e.arbitrationId);}}catch(e){this.warning='Index des contestations incomplet : '+e.message;}}
 attachment(value){const text=JSON.stringify(clone(value)),digest=sha(text),dir=path.join(this.root,'attachments'),file=path.join(dir,digest+'.json');fs.mkdirSync(dir,{recursive:true});if(!fs.existsSync(file)){const tmp=file+'.tmp-'+process.pid;fs.writeFileSync(tmp,text);try{fs.renameSync(tmp,file);}catch(e){try{fs.unlinkSync(tmp);}catch{}if(!fs.existsSync(file))throw e;}}return {sha256:digest,bytes:Buffer.byteLength(text),relativePath:path.relative(this.root,file)};}
 safeAttachment(value){try{return this.attachment(value);}catch(e){this.warning='Pièce jointe du journal incomplète : '+e.message;return {unavailable:true,reason:'non fournie'};}}
 record(type,data={}){try{fs.mkdirSync(path.dirname(this.file),{recursive:true});const event={schemaVersion:1,eventId:crypto.randomUUID(),at:new Date().toISOString(),gameInstanceId:this.instanceId,scenarioId:this.scenarioId,type,...clone(data)};const fd=fs.openSync(this.file,'a');try{fs.writeFileSync(fd,JSON.stringify(event)+'\n');fs.fsyncSync(fd);}finally{fs.closeSync(fd);}this.warning=null;return {ok:true,eventId:event.eventId};}catch(e){this.warning='Journal technique incomplet : '+e.message;return {ok:false,error:this.warning};}}
 start(kind,requestId,actor,input,before){const operationId=crypto.randomUUID();this.record('operation.started',{operationId,kind,requestId,actor,input:clone(input),beforeState:this.safeAttachment(before)});return operationId;}
 ai(operationId,prompt,schema){this.record('arbiter.requested',{operationId,prompt:this.safeAttachment(prompt),schema:this.safeAttachment(schema)});}
 aiResult(operationId,result){this.record('arbiter.responded',{operationId,response:this.safeAttachment(result)});}
 complete(operationId,after,arbitration){this.record('operation.committed',{operationId,afterState:this.safeAttachment(after),arbitration:clone(arbitration)});}
 fail(operationId,error){this.record('operation.failed',{operationId,error:{name:error?.name||'Error',code:error?.code||null,message:error?.message||'Erreur non fournie'}});}
 contest({requestId,arbitrationId:aid,reason,verdict,state}){if(this.contested.has(aid))return {ok:true,duplicate:true};const result=this.record('verdict.contested',{requestId,arbitrationId:aid,reason,verdict:clone(verdict),stateAtContest:this.safeAttachment(state),author:'Aurore Inchauspé',effectOnGame:'none'});if(result.ok)this.contested.add(aid);return result;}
 decorate(view){view.arbitration=(view.arbitration||[]).map((entry,index)=>{const id=arbitrationId(entry,index);return {...entry,id,contested:this.contested.has(id)};});view.journalStatus=this.warning?'incomplete':'available';return view;}
}
module.exports={ArbitrationJournal,arbitrationId};
