"use strict";
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const E=require('./engine'),{Store}=require('./store');
const means=(missing=0,extra={})=>({accepted:true,reason:'Contribution pertinente.',sufficient:missing===0,missing,delay:0,situationChanged:false,changeReason:'',dependsOn:[],...extra});
const plan=(missing=0,extra={})=>({...means(missing),title:'Un fait précis est établi',effect:'Le lieu de la réception est connu.',...extra});
function propose(s,kind='key',camp='phoebe',target='root-phoebe',rid='phoebe',p=plan()){const n=E.propose(s,camp,{kind,target,resource:rid,text:'Une contribution précise, par ces moyens, pour ce fait.'},p);/* Legacy-save fixture; fresh timing tested separately. */if(n&&kind!=='attack'){delete n.reactionThroughDay;if(n.dueDay!=null)n.dueDay=s.day+(p.delay||0);}return n;}
function next(s){s.day++;s.phase='player';s.spent={phoebe:false,commanditaire:false};}
const judgment=(outcomes=[],states=[],extra={})=>({outcomes,states,facts:[],fallenLocks:[],victory:[],...extra});
const out=(n,extra={})=>({id:n.id,success:true,reason:'Fait obtenu par ces moyens.',established:n.effect,losses:[],consume:[],recovery:[],maintainers:[],transfers:[],defenderBenefit:'',...extra});
function resolve(s,n,extra={}){if(n.reactionThroughDay!==undefined){s.day=Math.max(s.day,n.dueDay);s.phase='morning';delete s.morningMessages;}E.applyResolution(s,judgment([out(n,extra)]),E.immediateCandidates(s));}
function branch(s){return propose(s,'subgoal','phoebe','root-phoebe',null,plan(0,{title:'Phoebe connaît le lieu et l’heure de la réception.'}));}
function attack(s,missing=2){return propose(s,'attack','phoebe','convocation',null,plan(missing,{requiredCount:missing,delay:1}));}
function withStore(fn){return async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'charmed-v3-test-'));try{await fn(new Store(dir));}finally{for(const f of fs.readdirSync(dir))fs.unlinkSync(path.join(dir,f));fs.rmdirSync(dir);}};}

test('règles et journal v3, aucune migration silencieuse de v2',withStore(async store=>{assert.equal(E.initial().version,3);assert.match(store.file,/v3/);assert.equal(store.load().day,1);}));
test('une ressource suffit sur la voie principale si pertinente, résultat immédiat distinct du constat',()=>{const s=E.initial(),n=propose(s);assert.equal(n.status,'ready');assert.equal(n.dueDay,1);resolve(s,n);assert.equal(n.status,'acquired');assert.equal(E.node(s,'root-phoebe').status,'open');assert.equal(E.availability(s,E.resource(s,'phoebe')),'free');assert.equal(s.spent.phoebe,true);});
test('un seul coup, refus gratuit, gratuit après coup',()=>{const s=E.initial();propose(s,'key','phoebe','root-phoebe','phoebe',{accepted:false,reason:'Hors de portée'});assert.equal(s.spent.phoebe,false);propose(s);assert.throws(()=>propose(s),/déjà/);propose(s,'resource','phoebe',null,null,plan(0,{resource:{title:'Copie',description:'Notes recopiées',category:'objet'},costs:[]}));assert.equal(s.resources.at(-1).title,'Copie');});
test('aucun quota annoncé pour les contributions ouvertes',()=>{const s=E.initial(),n=propose(s,'key','phoebe','root-phoebe','phoebe',plan(2));assert.equal(n.missing,2);assert.equal(n.requiredCount,3);const v=E.publicView(s).nodes.at(-1);assert.equal(v.requirements,undefined);assert.equal(v.requiredCount,undefined);assert.equal(v.missing,undefined);assert.doesNotMatch(s.arbitration.at(-1).text,/2 ressource/);});
test('ajout pertinent et délai réel après préparation',()=>{const s=E.initial(),n=propose(s,'key','phoebe','root-phoebe','phoebe',plan(1));next(s);E.place(s,'phoebe',n.id,'carnet',means(0,{delay:2}));assert.equal(n.dueDay,4);assert.equal(E.immediateCandidates(s).length,0);s.day=4;resolve(s,n);assert.equal(n.status,'acquired');});
test('nouvelle ressource peut remplir le besoin, pas de recette fermée',()=>{const s=E.initial(),n=propose(s,'key','phoebe','root-phoebe','phoebe',plan(1));next(s);s.resources.push({id:'nouvelle',title:'Preuve matérielle',owner:'phoebe',category:'objet',availableDay:2});E.place(s,'phoebe',n.id,'nouvelle',means());assert.equal(n.status,'ready');});
test('deux engagements de la même ressource sont interdits',()=>{const s=E.initial();propose(s,'key','phoebe','root-phoebe','phoebe',plan(1));next(s);assert.throws(()=>propose(s),/disponible/);});
test('retrait payant limité aux clés et verrous : gel ou annulation',()=>{const s=E.initial(),n=propose(s,'key','phoebe','root-phoebe','phoebe',plan(1));next(s);E.place(s,'phoebe',n.id,'carnet',means());next(s);const result=E.withdraw(s,'phoebe','carnet');assert.equal(result.node.status,'preparing');assert.equal(E.resource(s,'carnet').heldBy,null);assert.equal(s.spent.phoebe,true);next(s);E.withdraw(s,'phoebe','phoebe');assert.equal(n.status,'removed');});
test('une attaque ne peut jamais perdre une ressource par retrait',()=>{const s=E.initial(),n=attack(s,1);s.day=n.revealDay;s.phase='player';s.spent={phoebe:false,commanditaire:false};E.place(s,'phoebe',n.id,'phoebe',means());next(s);assert.throws(()=>E.withdraw(s,'phoebe','phoebe'),/attaque/);});
test('le défenseur peut renforcer la cible révélée avec une ressource libre',()=>{const s=E.initial(),n=attack(s,1);s.day=n.revealDay;s.phase='player';s.spent={phoebe:false,commanditaire:false};E.place(s,'phoebe',n.id,'phoebe',means());s.phase='ai';s.spent.commanditaire=false;E.defend(s,'commanditaire',n.id,'gardien','Le gardien protège directement la convocation.',means());assert.deepEqual(n.defenders,['gardien']);assert.equal(E.availability(s,E.resource(s,'gardien')),'engaged');s.spent.commanditaire=false;assert.throws(()=>E.withdraw(s,'commanditaire','gardien'),/attaque/);});
test('un verrou peut viser une attaque ou une ressource adverse engagée',()=>{const s=E.initial(),n=attack(s,2);assert.doesNotThrow(()=>E.targetCheck(s,'commanditaire','lock',n.id));s.day=n.revealDay;s.phase='player';s.spent={phoebe:false,commanditaire:false};E.place(s,'phoebe',n.id,'phoebe',means(1));s.phase='ai';assert.doesNotThrow(()=>E.targetCheck(s,'commanditaire','lock','phoebe'));assert.throws(()=>E.targetCheck(s,'phoebe','lock','phoebe'),/adverse/);});
test('plusieurs clés sur un sous-état : pièces retenues jusqu’à preuve complète',()=>{const s=E.initial(),b=branch(s);next(s);const a=propose(s,'key','phoebe',b.id,'phoebe');resolve(s,a);assert.equal(b.status,'open');assert.equal(E.resource(s,'phoebe').heldBy,a.id);next(s);const k=propose(s,'key','phoebe',b.id,'nina');E.applyResolution(s,judgment([out(k)],[{id:b.id,value:true,reason:'Lieu et heure prouvés.',supports:[a.id,k.id]}]),E.immediateCandidates(s));assert.equal(b.status,'true');assert.equal(E.resource(s,'phoebe').heldBy,null);assert.equal(E.resource(s,'nina').heldBy,null);});
test('récupération variable, sans effet sur le fait jaune acquis',()=>{const s=E.initial(),n=propose(s);resolve(s,n,{recovery:[{id:'phoebe',days:2}]});assert.equal(E.availability(s,E.resource(s,'phoebe')),'recovering');assert.equal(n.established,n.effect);s.day=3;assert.equal(E.availability(s,E.resource(s,'phoebe')),'free');});
test('usage unique consommé ; une personne ne peut pas être consommée',()=>{const s=E.initial(),n=propose(s,'key','phoebe','root-phoebe','carnet');resolve(s,n,{consume:['carnet']});assert.equal(E.availability(s,E.resource(s,'carnet')),'lost');const t=E.initial(),k=propose(t);assert.throws(()=>resolve(t,k,{consume:['phoebe']}),/personne/);});
test('sous-états limités et phrase jamais action',()=>{const s=E.initial();assert.throws(()=>propose(s,'subgoal','phoebe','root-phoebe',null,plan(0,{title:'Interroger Élise'})),/jamais une action/);for(let i=0;i<3;i++){branch(s);next(s);}assert.throws(()=>branch(s),/emplacements/);});
test('une clé prête ne prouve pas un état, ni une clé destinée à une autre cible',()=>{const s=E.initial(),b=branch(s);next(s);const n=propose(s,'key','phoebe',b.id,'phoebe',plan(0,{delay:1}));assert.throws(()=>E.applyResolution(s,judgment([],[{id:b.id,value:true,reason:'Simple intention',supports:[n.id]}]),[]),/prouve/);s.day++;resolve(s,n);assert.throws(()=>E.applyResolution(s,judgment([],[{id:'root-phoebe',value:true,reason:'Mauvaise cible',supports:[n.id]}]),[]),/prouve/);});
test('verrou permis sur racine, branche et chaque clé adverse, jamais soi',()=>{const s=E.initial(),a=propose(s);next(s);const b=branch(s);for(const id of ['root-phoebe',a.id,b.id])assert.doesNotThrow(()=>E.targetCheck(s,'commanditaire','lock',id));assert.throws(()=>E.targetCheck(s,'phoebe','lock',a.id),/adverse/);});
function lockSetup(maintainers=[]){const s=E.initial(),k=propose(s);resolve(s,k);s.phase='ai';const l=propose(s,'lock','commanditaire',k.id,'gardien');resolve(s,l,{maintainers});return {s,k,l};}
test('un verrou ne regèle pas les anciennes pièces libérées et ne détruit pas le fait',()=>{const {s,k}=lockSetup(['gardien']);assert.equal(E.availability(s,E.resource(s,'phoebe')),'free');assert.equal(k.status,'acquired');assert.equal(k.established,k.effect);});
test('gardien nécessaire détruit : verrou tombe ; porte durable : auteur libéré',()=>{const a=lockSetup(['gardien']);E.resource(a.s,'gardien').lost=true;E.refresh(a.s);assert.equal(a.l.status,'removed');const b=lockSetup();assert.equal(E.resource(b.s,'gardien').heldBy,null);E.resource(b.s,'gardien').lost=true;E.refresh(b.s);assert.equal(b.l.status,'active');});
test('clé spécifique réalisée lève seulement son verrou',()=>{const {s,l}=lockSetup();next(s);const k=propose(s,'key','phoebe',l.id,'nina');assert.equal(l.status,'active');resolve(s,k);assert.equal(l.status,'removed');});
test('une question et une réponse soumise, refus terminal sans correction',()=>{const s=E.initial(),n=propose(s,'key','phoebe','root-phoebe','phoebe',plan(1));s.phase='ai';E.question(s,'commanditaire',n.id,'Par quel moyen exact ?');assert.equal(E.availability(s,E.resource(s,'phoebe')),'frozen');s.phase='player';E.answer(s,'phoebe',s.questions[0].id,'Une explication incomplète',means(0,{accepted:false}));assert.equal(n.status,'removed');assert.equal(s.questions[0].resolved,true);assert.throws(()=>E.answer(s,'phoebe',s.questions[0].id,'Une correction meilleure',means()),/seule réponse/);});
test('réponse possible mais moyens manquants : dégel, préparation et chemin fixé',()=>{const s=E.initial(),n=propose(s);s.phase='ai';E.question(s,'commanditaire',n.id,'Comment accéder à ce lieu ?');s.phase='player';E.answer(s,'phoebe',s.questions[0].id,'Avec un accès autorisé et un guide présent.',means(2));assert.equal(n.status,'preparing');assert.equal(n.missing,2);assert.equal(E.publicView(s).nodes.at(-1).suspended,false);s.phase='ai';assert.throws(()=>E.question(s,'commanditaire',n.id,'Autre question ?'),/déjà/);});
test('questions sur états également, pendant le bon passage',()=>{const s=E.initial(),n=propose(s);assert.throws(()=>E.question(s,'commanditaire',n.id,'Comment faire ?'),/passage/);s.phase='ai';E.question(s,'commanditaire','root-phoebe','Comment faire ?');assert.equal(E.publicView(s).nodes.find(n=>n.id==='root-phoebe').suspended,true);});
test('suspension propagée aux dépendances sans suspendre les autres chemins',()=>{const s=E.initial(),a=propose(s);resolve(s,a);next(s);const b=propose(s,'key','phoebe','root-phoebe','nina',plan(0,{dependsOn:[a.id]}));s.phase='ai';E.question(s,'commanditaire',a.id,'Comment connaissez-vous ce fait ?');assert.equal(E.publicView(s).nodes.find(n=>n.id===b.id).suspended,true);assert.equal(E.immediateCandidates(s).length,0);});
test('attaque : déclaration sans pièce, révélation seulement au matin avec nombre et date',()=>{const s=E.initial(),n=attack(s);assert.equal(n.pieces.length,0);let v=E.publicView(s).nodes.at(-1);for(const key of ['missing','requiredCount','dueDay','effect'])assert.equal(v[key],undefined);s.phase='morning';E.morning(s,judgment());v=E.publicView(s).nodes.at(-1);assert.equal(v.requiredCount,2);assert.equal(v.dueDay,4);assert.match(s.radio.at(-1).text,/2 pièces/);assert(!s.radio.at(-1).text.includes('Risques'));});
test('attaque incomplète : échec obligatoire et avantage défenseur obligatoire',()=>{const s=E.initial(),n=attack(s);s.day=4;let list=E.immediateCandidates(s);assert.equal(list[0].forcedFailure,true);assert.throws(()=>resolve(s,n),/incomplète/);assert.throws(()=>resolve(s,n,{success:false}),/défenseur/);resolve(s,n,{success:false,defenderBenefit:'Le gardien repère le poste d’observation abandonné et connaît son emplacement.'});assert.equal(n.status,'failed');assert(s.facts.includes(n.defenderBenefit));});
test('attaque : pas d’ajout après date, pas de nombre changé',()=>{const s=E.initial(),n=attack(s);next(s);assert.throws(()=>E.place(s,'phoebe',n.id,'phoebe',means(3,{situationChanged:true,changeReason:'Un fait nouveau'})),/nombre/);s.day=n.dueDay;assert.throws(()=>E.place(s,'phoebe',n.id,'phoebe',means(1)),/date/);});
test('attaque complète : vol transfère la cible et restitue les moyens',()=>{const s=E.initial(),n=attack(s,1);next(s);E.place(s,'phoebe',n.id,'phoebe',means());s.day=n.dueDay;resolve(s,n,{transfers:[{id:'convocation',owner:'phoebe'}]});assert.equal(E.resource(s,'convocation').owner,'phoebe');assert.equal(E.resource(s,'phoebe').heldBy,null);});
test('question avant échéance : droit à réponse préservé sans délai pour assembler',()=>{const s=E.initial(),k=propose(s);resolve(s,k);next(s);const a=attack(s,1);a.dependsOn=[k.id];next(s);E.place(s,'phoebe',a.id,'nina',means());s.phase='ai';E.question(s,'commanditaire',k.id,'Par quel chemin établi ?');s.phase='morning';E.morning(s,judgment());assert.equal(s.day,a.dueDay);assert.equal(a.deadlineReady,true);assert.equal(a.status,'ready');E.answer(s,'phoebe',s.questions[0].id,'Par la conversation déjà réalisée et le témoignage.',means());assert.equal(E.immediateCandidates(s).length,1);resolve(s,a);assert.equal(a.status,'resolved');});
test('question sans réponse : reste suspendue sans retrait automatique de la clé',()=>{const s=E.initial(),k=propose(s);s.phase='ai';E.question(s,'commanditaire',k.id,'Par quel chemin établi ?');next(s);E.endPassage(s,'phoebe');assert.equal(k.status,'ready');assert.equal(s.questions[0].resolved,false);assert.equal(s.questions[0].opportunityPassed,true);assert.equal(E.publicView(s).nodes.at(-1).suspended,true);});
test('calendrier J3 : deux copies automatiques, libres, sans preuve et sans coup',()=>{const s=E.initial();s.day=2;s.phase='morning';E.morning(s,judgment());const copies=s.resources.filter(r=>r.id.startsWith('event-3-'));assert.equal(copies.length,2);assert.notEqual(copies[0].id,copies[1].id);assert.deepEqual(new Set(copies.map(r=>r.owner)),new Set(['phoebe','commanditaire']));assert(copies.every(r=>E.availability(s,r)==='free'));assert.equal(s.nodes.length,2);assert.equal(s.spent.phoebe,false);});
test('ressource gratuite hors passage sauf Radio ; personnage unique non duplicable',()=>{const s=E.initial();s.phase='ai';const p=plan(0,{resource:{title:'Copie du carnet',description:'Une copie',category:'objet'},costs:[]});propose(s,'resource','phoebe',null,null,p);assert.equal(s.spent.phoebe,false);p.resource={title:'Phoebe Halliwell',description:'Personnage',category:'personnage'};assert.throws(()=>propose(s,'resource','phoebe',null,null,p),/unique/);s.phase='morning';assert.throws(()=>propose(s,'resource','phoebe',null,null,p),/Radio/);});
test('ingrédient perdu : potion impossible et aucun coup perdu',()=>{const s=E.initial();E.resource(s,'carnet').lost=true;assert.throws(()=>propose(s,'resource','phoebe',null,null,plan(0,{resource:{title:'Potion',description:'Potion définie',category:'objet'},costs:['carnet']})),/Ingrédient/);assert.equal(s.spent.phoebe,false);});
test('objectif vrai mais encore attaquable : aucune victoire prématurée',()=>{const s=E.initial(),k=propose(s);E.applyResolution(s,judgment([out(k)],[{id:'root-phoebe',value:true,reason:'Fait complet actuel',supports:[k.id]}],{victory:[{root:'root-phoebe',allConditions:true,secure:false,reason:'L’adversaire possède encore des moyens.'}]}),E.immediateCandidates(s));assert.equal(s.result,null);});
test('preuve complète assurée : victoire ; branches optionnelles non imposées',()=>{const s=E.initial(),b=branch(s);next(s);const k=propose(s);E.applyResolution(s,judgment([out(k)],[{id:'root-phoebe',value:true,reason:'Toutes les conditions établies',supports:[k.id]}],{victory:[{root:'root-phoebe',allConditions:true,secure:true,reason:'Plus aucun chemin adverse réalisable.'}]}),E.immediateCandidates(s));assert.equal(s.result.winner,'phoebe');assert.equal(b.status,'open');});
test('maintien rompu ne se répare pas en victoire à la date finale',()=>{const s=E.initial(),r=E.node(s,'root-phoebe');r.status='true';r.goalMode='maintain';E.applyResolution(s,judgment([],[{id:r.id,value:false,reason:'Protection rompue.',supports:[]}]),[]);r.status='true';s.day=12;E.applyResolution(s,judgment([],[],{victory:[{root:r.id,allConditions:true,secure:true,reason:'Protection rétablie seulement maintenant.'}]}),[]);assert.equal(s.result.winner,null);assert.equal(r.maintenanceBroken,true);});
test('échéance sans vainqueur, aucun coup payé après échéance',()=>{const s=E.initial();s.day=11;s.phase='morning';E.morning(s,judgment());assert.equal(s.result.winner,null);const t=E.initial();t.day=12;assert.throws(()=>propose(t),/échéance/);});
test('lot de résolutions incomplet refusé',()=>{const s=E.initial();propose(s);assert.throws(()=>E.applyResolution(s,judgment(),E.immediateCandidates(s)),/une fois/);});
test('journal : transaction atomique, verrou, rejeu et révision',withStore(async store=>{let done;const p=store.transact(0,'request-0001',async s=>{await new Promise(r=>done=r);s.facts.push('Test');});await assert.rejects(()=>store.transact(0,'request-0002',()=>{}),/cours/);done();await p;await assert.rejects(()=>store.transact(0,'request-0003',()=>{}),/changé/);await assert.rejects(()=>store.transact(1,'request-0004',s=>{s.day=99;throw new Error('échec');}),/échec/);assert.equal(store.load().day,1);assert.equal((await store.transact(0,'request-0001',()=>{throw Error();})).revision,1);}));
test('canon : une lacune signale sans refuser, une contradiction sourcée refuse',()=>{const C=require('./canon');
 const lacune=C.verify({accepted:true,canon:{status:'unverified',reason:'Pouvoir inconnu'}});
 assert.equal(lacune.accepted,true);assert.match(lacune.canonNote,/non documenté/);
 const horsPeriode=C.verify({accepted:true,canon:{status:'verified',facts:['zankou-premonition']}});
 assert.equal(horsPeriode.accepted,true);assert.match(horsPeriode.canonNote,/plateau/);
 assert.equal(C.verify({accepted:true,canon:{status:'verified',facts:['initial-powers']}}).accepted,true);
 assert.equal(C.verify({accepted:true,canon:{status:'ordinary',facts:[]}}).accepted,true);
 assert.equal(C.verify({accepted:true,canon:{status:'contradicted',facts:['initial-powers'],reason:'Le corpus l’exclut.'}}).accepted,false);});

test('aucun usage implicite d’une carte non engagée dans le résultat',()=>{const s=E.initial(),n=propose(s);assert.throws(()=>resolve(s,n,{usedResources:['phoebe','dossier-reception']}),/réellement engagée/);assert.equal(n.status,'ready');});
test('une identité canonique ne se duplique pas avec un nom court',()=>{const s=E.initial();assert.throws(()=>propose(s,'resource','phoebe',null,null,plan(0,{resource:{title:'Phoebe',description:'La même sœur',category:'personnage',canonicalId:'nouveau-id'},costs:[]})),/unique/);});
test('une ancienne preuve retirée ne donne pas de victoire par statut vrai resté affiché',()=>{const s=E.initial(),k=propose(s);resolve(s,k);const root=E.node(s,'root-phoebe');root.status='true';root.supports=[k.id];k.status='removed';E.applyResolution(s,judgment([],[],{victory:[{root:root.id,allConditions:true,secure:true,reason:'Ancienne preuve invalide.'}]}),[]);assert.equal(s.result,null);});

test('attaque à échéance : une occasion de répondre non saisie ne prolonge pas la tentative',()=>{const s=E.initial(),k=propose(s);resolve(s,k);next(s);const a=attack(s,1);a.dependsOn=[k.id];next(s);E.place(s,'phoebe',a.id,'nina',means());s.phase='ai';E.question(s,'commanditaire',k.id,'Par quel chemin établi ?');s.phase='morning';E.morning(s,judgment());E.endPassage(s,'phoebe');assert.equal(E.immediateCandidates(s)[0].forcedFailure,true);resolve(s,a,{success:false,defenderBenefit:'Le gardien découvre la tentative de diversion et en connaît le lieu.'});assert.equal(a.status,'failed');assert.equal(k.status,'acquired');});

test('attaque : au moins une ressource libre en main, pour les deux camps, sans engagement automatique',()=>{
 for(const camp of ['phoebe','commanditaire']){
  const s=E.initial();s.phase=camp==='phoebe'?'player':'ai';const target=camp==='phoebe'?'convocation':'phoebe';
  for(const r of s.resources.filter(r=>r.owner===camp))r.availableDay=3;
  assert.throws(()=>E.targetCheck(s,camp,'attack',target),/ressource disponible/);
  const r=s.resources.find(r=>r.owner===camp);r.availableDay=1;
  assert.doesNotThrow(()=>E.targetCheck(s,camp,'attack',target));
  const n=propose(s,'attack',camp,target,null,plan(1,{requiredCount:1,delay:1}));
  assert.equal(n.pieces.length,0);assert.equal(r.heldBy,null);assert.equal(s.spent[camp],true);
 }
});

test('état questionné non arbitré sans réponse, rejet conserve son objectif',()=>{const s=E.initial();s.phase='ai';E.question(s,'commanditaire','root-phoebe','Comment est-ce possible ?');E.applyResolution(s,judgment([],[{id:'root-phoebe',value:true,reason:'Ne pas juger',supports:[]}]),[]);assert.equal(E.node(s,'root-phoebe').status,'open');s.phase='player';E.submitAnswer(s,'phoebe',s.questions[0].id,'Ma justification');E.adjudicateAnswer(s,s.questions[0].id,means(0,{accepted:false}));assert.equal(E.node(s,'root-phoebe').status,'open');assert.equal(s.nodes.length,2);});
test('renfort pertinent possible sur clé prête, un coup et pas de double engagement',()=>{const s=E.initial(),n=propose(s);next(s);E.place(s,'phoebe',n.id,'carnet',means());assert.equal(n.pieces.length,2);assert.equal(s.spent.phoebe,true);assert.equal(E.resource(s,'carnet').heldBy,n.id);});
test('nouvelle contribution : jour de réaction complet identique aux deux camps',()=>{for(const camp of ['phoebe','commanditaire']){const s=E.initial();s.phase=camp==='phoebe'?'player':'ai';const r=s.resources.find(r=>r.owner===camp&&E.availability(s,r)==='free');const n=E.propose(s,camp,{kind:'key',target:'root-'+camp,resource:r.id,text:'Une preuve directe de la condition finale.'},plan());assert.equal(n.dueDay,2);s.phase='morning';assert.equal(E.immediateCandidates(s).length,0);E.prepareMorning(s);assert.equal(s.day,2);assert.equal(E.immediateCandidates(s).length,0);E.finishMorning(s,judgment());assert.equal(E.immediateCandidates(s).length,0);s.phase='morning';assert.equal(E.immediateCandidates(s).length,1);}});
test('nouvelle pose : réaction renouvelée sans raccourcir un délai réel',()=>{const s=E.initial();const n=E.propose(s,'phoebe',{kind:'key',target:'root-phoebe',resource:'phoebe',text:'Un effet avec délai réellement nécessaire.'},plan(0,{delay:4}));next(s);E.place(s,'phoebe',n.id,'carnet',means());assert.equal(n.reactionThroughDay,3);assert.equal(n.dueDay,5);s.phase='morning';assert.equal(E.immediateCandidates(s).length,0);});
test('un lieu ne peut être ni attaqué ni volé',()=>{
 const s=E.initial();
 assert.throws(()=>E.targetCheck(s,'commanditaire','attack','refuge'),/lieu ne peut être ni attaqué ni volé/i);
 const n=propose(s,'key','phoebe','root-phoebe','refuge');
 assert.throws(()=>resolve(s,n,{consume:['refuge']}),/lieu ne peut pas être consommé/i);
 assert.throws(()=>resolve(s,n,{losses:['refuge']}),/lieu ne peut pas être détruit ou perdu/i);
});

test('une clé peut contester puis transférer le contrôle d’un lieu explicitement déterminant',()=>{
 const s=E.initial();s.phase='ai';
 const n=E.propose(s,'commanditaire',{kind:'key',target:'root-commanditaire',resource:'commanditaire',text:'Une mission établit effectivement le contrôle du refuge.'},plan(0,{mainCondition:'Le refuge est contrôlé.',locations:['refuge']}));
 s.day=n.dueDay;s.phase='morning';delete s.morningMessages;
 E.applyResolution(s,judgment([out(n,{established:'La Chambre chez Nina est occupée et contrôlée par le commanditaire.',controlChanges:[{id:'refuge',owner:'commanditaire'}]})]),E.immediateCandidates(s));
 assert.equal(E.resource(s,'refuge').owner,'commanditaire');
 assert.equal(E.resource(s,'refuge').controlHistory.at(-1).proof,n.id);
});

test('un simple accès ne peut pas transférer le contrôle du lieu',()=>{
 const s=E.initial();s.phase='ai';
 const n=E.propose(s,'commanditaire',{kind:'key',target:'root-commanditaire',resource:'commanditaire',text:'Une mission ouvre seulement un accès au refuge.'},plan(0,{mainCondition:'Un accès est ouvert.',locations:['refuge']}));
 s.day=n.dueDay;s.phase='morning';delete s.morningMessages;
 assert.throws(()=>E.applyResolution(s,judgment([out(n,{established:'Un accès au refuge est ouvert.',controlChanges:[{id:'refuge',owner:'commanditaire'}]})]),E.immediateCandidates(s)),/établir explicitement le contrôle ou l’occupation/i);
 assert.equal(E.resource(s,'refuge').owner,'phoebe');
});
