from pathlib import Path
import json, csv, hashlib

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[2]
# Données éditoriales rédigées à partir des sources réellement recherchées le 8 septembre 2026.
# Colonnes : identifiant | nom | nature | épisodes | pages sources | faits contextualisés | limites | carte.
RAW=r'''org-nettoyeurs|Les Nettoyeurs|institution|S06E03,S06E19|The_Cleaners|Chargés par le Tribunal de préserver le secret magique, ils peuvent modifier événements et souvenirs. Après le dragon de Wyatt, ils effacent son existence avant que les sœurs obtiennent son retour. Dans le procès de Darryl, ils fabriquent une version des événements qui le fait condamner.|Leur mission dite neutre peut léser un innocent. Leur apparition tardive ne justifie pas rétroactivement toutes les crises antérieures. Ne pas déduire une intervention à chaque sort ni une invincibilité universelle.|Les Nettoyeurs — Agents du secret magique, capables de modifier des événements et les souvenirs qui s’y rattachent. Leurs interventions relèvent du Tribunal.
org-tribunal|Le Tribunal|institution|S06E19|The_Tribunal|Conseil mixte de Fondateurs et de démons : Adair et Aramis, Thrask et Crill dans la page secondaire. Gideon défend les sœurs ; Barbas est leur adversaire au procès, pas un juge. L’affaire concerne les modifications des Nettoyeurs et le sort de Darryl. Le procès examine aussi l’usage des pouvoirs des sœurs.|Les noms des juges reposent sur le wiki ; la transcription consultée confirme la composition mixte, les rôles judiciaires et les événements réécrits. La plaisanterie sur quatre juges ne définit pas une règle de départage. Exclure le nouveau Tribunal des comics.|Le Tribunal — Conseil de Fondateurs et de démons chargé du secret magique. Examine des différends concernant l’usage de la magie et les interventions des Nettoyeurs.
org-confrerie|Confrérie de l’Épine — Brotherhood of the Thorn|confrérie|S03E19,S03E20|Brotherhood_of_the_Thorn;The_Demon_Who_Came_in_from_the_Cold/Plot|Société de démons d’élite au service de la Source, notamment Raynor, Vornac et Belthazor. Elle infiltre les affaires humaines. Lors du retour de Cole, Klea vérifie son récit ; l’appartenance passée ne suffit donc pas à garantir la confiance. Un serment de sang relie les membres.|L’athame et le serment ne donnent pas les pouvoirs de tous les membres. Le wiki n’est pas cohérent sur tous les survivants, notamment Klea et Jassa : destruction complète non retenue. Traduction française de travail à contrôler au doublage.|Confrérie de l’Épine — Société démoniaque d’élite pratiquant l’infiltration et liée par un serment de sang. Dispose de relais dans les affaires humaines.
org-avatars|Les Avatars|collectif|S05E12,S07E12,S07E13|Avatars;Beta|Collectif notamment représenté par Alpha, Beta et Gamma ; Cole puis Leo le rejoignent à des périodes différentes. Leur puissance commune permet des altérations de réalité et du temps. Leur Utopia supprime le conflit en altérant les réactions et en éliminant les personnes perturbatrices. La mort de Beta affaiblit l’ensemble.|Une réserve collective sollicitée ou diminuée n’est pas une puissance illimitée. Adhésion et simple sympathie restent distinctes. Utopia ne prouve pas un libre consentement ; ne pas importer les morts et remaniements des comics.|Les Avatars — Collectif partageant une réserve de puissance qui permet de transformer la réalité. Cherche à dépasser le conflit entre le Bien et le Mal.
org-fondateurs|Les Fondateurs — The Elders|institution|S05E22,S05E23,S06E23,S07E16|The_Elders|Conseil supervisant les Êtres de lumière et leurs missions. Les Titans menacent effectivement ses membres ; Leo accède à cette fonction en fin de saison 5. Les projets de Gideon et l’épreuve ultérieure de Leo montrent que la fonction ne produit pas une volonté unanime.|La fiche collective elders existe déjà et contient des transcriptions mieux vérifiées que cette nouvelle recherche. Conserver ces preuves ; ne pas les remplacer par le wiki. Un membre ne représente pas nécessairement une décision du Conseil.|Les Fondateurs — Autorité magique supervisant les Êtres de lumière. Confient des missions et interviennent dans leur statut ; leurs membres peuvent être en désaccord.
org-etres-lumiere|Réseau des Êtres de lumière|réseau de service|S03E11|Whitelighter;Natalie_%28Whitelighter%29|Des protecteurs guident des sorcières sous la supervision des Fondateurs. Natalie intervient auprès des sœurs lorsque Leo lui confie temporairement leur encadrement face à Eames. Leur service comporte protection, conseils et transmission ; l’appel d’un protégé permet habituellement un contact.|Intitulé descriptif : l’espèce entière n’est pas une personne morale unique. Attribution des protégés, disponibilité, statut et pouvoirs du représentant doivent être datés. L’appel n’établit pas une arrivée garantie dans toutes les dimensions ou circonstances.|Réseau des Êtres de lumière — Protecteurs et guides de sorcières, organisés autour de missions et de protégés confiés à chacun.
org-ecole-magie|École de magie|institution|S06E14,S07E02,S08E22|Magic_School;The_Bare_Witch_Project/Plot|Institution d’enseignement magique dirigée notamment par Gideon, puis prise en charge par Paige et Leo selon la période. Paige défend son maintien au début de la saison 7. Les enseignants et les élèves constituent un collectif de formation distinct du bâtiment. La fin de la série montre Leo y enseignant.|L’accès au lieu ne donne pas automatiquement la coopération de toute l’école. Dater fermeture, occupation et direction. Exclure les ailes de la Halliwell Academy et les cursus tirés des romans ou comics. Les protections ne sont pas une invulnérabilité des occupants.|École de magie — Institution réunissant enseignants, élèves et connaissances pour l’apprentissage de la magie. Sa direction et ses activités varient selon la période.
org-conseil|Le Conseil démoniaque|conseil|S02E22|The_Council;Be_Careful_What_You_Witch_For/Script|Conseil de cinq démons qui charge un Dragon Warlock et un génie de prendre les sœurs au piège des vœux. Les commanditaires dirigent une opération indirecte et peuvent rappeler leur intermédiaire à l’ordre.|L’assimilation ultérieure à la Triade est une hypothèse de continuité du wiki et une annotation de transcription, pas une identité explicitement établie par une réplique. Le conseil des couronnements de saison 4 ne doit pas être fusionné sans arbitrage.|Conseil démoniaque — Groupe de dirigeants démoniaques qui commande des opérations et emploie des intermédiaires contre les Charmed Ones.
org-triade|La Triade|conseil|S03E07,S08E16,S08E21,S08E22|The_Triad|Commanditaires de Belthazor en saison 3, puis organisateurs de la manipulation de Christy et Billie en saison 8. Asmodeus, Baliel et Candor sont associés aux incarnations tardives. Les destructions corporelles et formes spirituelles doivent être distinguées. Dumain sert leur projet et espère être admis : ce n’est pas la même position qu’un membre.|Deux fiches triad existent déjà dans personnages.json et magie-demons.json. Conserver la distinction membres, corps et périodes ainsi que leurs sources de transcription. Aucun automatisme d’immortalité ou de destruction définitive à partir d’une seule confrontation.|La Triade — Groupe dirigeant démoniaque agissant par ses agents et ses manipulations. La cohésion de ses membres contribue à sa puissance.
org-ordre|L’Ordre — The Order|culte|S06E12|The_Order;Prince_Charmed|Culte démoniaque persuadé que Wyatt est la réincarnation de son chef. Ses acolytes cherchent à altérer sa moralité avec un sceptre et à le soustraire à sa famille. Leur chef intérimaire et leurs subterfuges ne suffisent pas à obtenir l’adhésion de l’enfant ; des acolytes prennent la fuite.|La réincarnation est leur croyance, pas un fait confirmé. Une page de Livre des Ombres signalée comme non utilisée à l’écran évoque des capacités et un contre-moyen : elle ne vaut pas preuve télévisée. Ne pas conclure à l’extinction complète du culte.|L’Ordre — Culte démoniaque recherchant la réincarnation de son dirigeant. Dispose d’acolytes et de moyens destinés à influencer la moralité de sa cible.
org-ordo|Ordo Malorum|hiérarchie démoniaque|S02E15|Litvack;Level_Two_Demon;Give_Me_a_Sign|Litvack est présenté comme un général de cette hiérarchie maléfique. Ses serviteurs exécutent des missions, notamment dans l’intrigue où Bane et Prue sont menacés. La documentation associe le groupe à un commandement militaire démoniaque.|La structure complète et l’effectif ne sont pas établis. Les descriptions reproduisant le Livre des Ombres restent des reproductions secondaires. Ne pas donner à tous les soldats les pouvoirs personnels de Litvack ni confondre ce groupe avec tout le Mal.|Ordo Malorum — Hiérarchie démoniaque comprenant des généraux et des serviteurs chargés de leurs opérations.
org-cour-source|Cour et hiérarchie de la Source|régime et entourage|S03E22,S04E13,S04E19,S04E21|The_Source_of_All_Evil;Unnamed_Half-Faced_Source|La Source gouverne à travers des agents, conseillers et exécutants. Les changements de titulaire et les intrigues de cour structurent les alliances démoniaques. Ce dossier décrit l’entourage et le commandement, tandis que la Source elle-même reste un personnage ou un titre.|Intitulé de classement proposé. Ne pas transformer chaque démon en subordonné loyal : rivalités, dissidences et succession existent. Les pouvoirs du souverain ne sont pas des capacités communes à la cour. Composition exacte à fixer selon l’épisode.|Cour de la Source — Entourage de dirigeants, conseillers et agents démoniaques réunis autour du détenteur du titre de Source.
org-cavaliers|Les Quatre Cavaliers de l’Apocalypse|équipe|S02E21|Four_Horsemen_of_the_Apocalypse|Guerre, Mort, Discorde et Famine préparent l’Apocalypse au service de la Source. La disparition de Guerre dans une autre dimension compromet leur opération ; une négociation survient parce que Prue y est aussi prisonnière. La Source punit leur échec.|Ne pas substituer les quatre figures de la tradition biblique aux quatre noms de la série. Le cavalier Mort n’est pas l’Ange de la mort. Leur coopération montre une dépendance opérationnelle, sans fournir une règle générale de nombre pour d’autres groupes.|Les Quatre Cavaliers — Équipe de Guerre, Mort, Discorde et Famine, mobilisée pour provoquer l’Apocalypse et coordonner ses effets.
org-valkyries|L’ordre des Valkyries|ordre guerrier|S06E01,S06E02|Valkyrie;Valhalley_of_the_Dolls%2C_Part_1/Script|Communauté de guerrières, notamment Freyja, Mist et Kara, qui recrute des âmes de guerriers et les entraîne pour une bataille finale. Leo se trouve captif dans ce dispositif à la suite de l’accord passé par Chris. Des guerriers échappés deviennent une menace dans le monde humain.|La mission guerrière ne garantit pas le consentement de tous les recrutés. Les pendentifs, transformations et accès ne rendent pas tout porteur membre fidèle de l’ordre. Ne pas importer les règles des mythes nordiques comme règles de Charmed.|Valkyries — Ordre de guerrières recrutant et entraînant des âmes combattantes. Possède ses traditions, ses équipements et sa discipline.
org-academie-kellman|Académie de Kellman|organisation de recrutement|S03E12|The_Academy;Kellman|Kellman dirige un dispositif qui attire des humains par la réussite avant de les former à devenir démons. Le parcours de Tom montre entraînement, grades et meurtre d’un innocent comme étape décisive. Son sauvetage interrompt sa transformation.|Ne pas confondre cette académie avec celle de Ludlow, qui reçoit des enfants dotés de pouvoirs. La mort de Kellman ne documente pas le devenir de chaque recruteur ni une disparition mondiale du système.|Académie de Kellman — Organisation recrutant des humains et les formant à la condition démoniaque par un parcours d’épreuves et de grades.
org-academie-ludlow|Académie démoniaque de Ludlow|institution|S04E12|Tyler_Michaels;Lost_and_Bound|Ludlow exploite des enfants aux pouvoirs utiles à la Source. Des parents d’accueil démoniaques cherchent à lui livrer Tyler, dont la pyrokinesie intéresse cette formation de futurs gardes. Les sœurs interviennent contre ce recrutement contraint.|Ne pas importer les aventures de Tyler avec les Archai des comics. Le recrutement d’enfants magiques distingue ce dispositif de l’académie de Kellman. L’état de tous les autres élèves et recruteurs après l’épisode reste à vérifier.|Académie de Ludlow — Institution démoniaque recrutant des enfants dotés de pouvoirs pour les former au service de la Source.
org-zodiaques|Les douze Zodiaques|collège de gardiens|S08E14|The_Chinese_Zodiacs|Douze gardiens préservent un cycle annuel par la transmission du bâton de Bouddha. La mort du Coq affaiblit le collectif. Ils accusent d’abord Piper de vol avant de comprendre sa protection de l’objet. Lo Pan, d’abord gardien du jardin, remplace finalement le Coq puis transmet le bâton.|Les barrières sont observées collectivement. Les périodes de détention du bâton contraignent sa transmission ; être le successeur attendu n’autorise pas à le prendre trop tôt. Ne pas présenter ces règles fictionnelles comme celles d’une religion réelle.|Les douze Zodiaques — Collège de gardiens assurant la transmission annuelle du bâton de Bouddha et la continuité du cycle qu’il soutient.
org-titans|Trio des Titans libérés|coalition|S05E22,S05E23|The_Titans;Oh_My_Goddess%21_Part_1/Plot|Cronus, Demitrius et Meta cherchent à reprendre le pouvoir et à se venger des Fondateurs après leur libération. Leurs capacités sont considérables, mais leur entente est fragile : Cronus tue Meta malgré sa résistance aux attaques des sœurs.|Il s’agit du trio montré, pas d’un inventaire de toutes les divinités grecques. Les graphies Demitrius et Demetrius varient dans les pages. Résistance à certaines attaques et impossibilité absolue d’être détruit sont différentes.|Titans libérés — Coalition de puissants êtres anciens cherchant à rétablir leur domination et à renverser les Fondateurs.
org-leprechauns|Communauté et conseil des Leprechauns|communauté organisée|S05E17|Head_Councilman;Lucky_Charmed|Face à Saleel, Seamus et un groupe de Leprechauns mettent leur chance en commun. Leur conseil hésite entre fuite et résistance ; après la mort de Seamus, la communauté se mobilise et le conseiller dirige l’intervention. Or et shillelaghs participent à leurs pratiques.|La page qualifie le conseiller de chef présumé de cette tribu : ne pas en faire le souverain de tous les Leprechauns. La solidarité observée dans cette crise ne signifie pas une aide automatique à chaque sollicitation.|Communauté des Leprechauns — Groupe organisé autour d’un conseil, capable de réunir ses moyens liés à la chance et à ses instruments magiques.
org-charmed|Les Charmed Ones|sororité|S01E01,S04E01|The_Charmed_Ones|Sororité issue de la lignée Warren et vouée à protéger les innocents. Prue, Piper et Phoebe forment le trio des premières saisons ; après la mort de Prue, Paige rejoint Piper et Phoebe et reconstitue le Pouvoir des Trois.|Quatre sœurs identifiées dans l’histoire ne signifient pas quatre membres simultanément actifs dans un même trio. Les pouvoirs et altérations individuels restent datés. Les développements posthumes de Prue tirés des comics sont exclus.|Les Charmed Ones — Sororité de trois sorcières unies par le Pouvoir des Trois. Leur magie collective complète les aptitudes propres à chacune.
org-rowe|Coven Rowe|fratrie|S01E18|Rowe_Coven|Greg et Paul Rowe veulent que leur demi-frère Brendan complète une triade maléfique en tuant un innocent. Brendan refuse cette trajectoire et cherche à devenir prêtre. La fratrie se désagrège au lieu de réaliser le destin annoncé.|La prophétie et les ambitions des deux frères ne suppriment pas le choix de Brendan. Distinguer un groupe projeté, sa réunion effective et un pouvoir collectif réalisé. Ne pas distribuer une puissance annoncée comme déjà disponible.|Coven Rowe — Fratrie de warlocks liée à la perspective d’un pouvoir collectif maléfique, avec des engagements profondément divergents.
org-phoenix|Lignée des Phoenix|clan d’assassines|S06E10|Phoenix_%28Assassin_Witches%29|Lignée de sorcières assassines à laquelle appartiennent Lynn et Bianca. La Bianca adulte d’un futur dominé par Wyatt reçoit une mission concernant Chris, mais son attachement à lui contrarie sa fidélité attendue. Le signe du phénix est décrit comme une marque de naissance.|Ne pas confondre marque héréditaire et tatouage d’adhésion. Bianca enfant du présent et adulte du futur ne sont pas interchangeables. La réputation du clan ne fixe pas les choix de chaque membre ni un catalogue de pouvoirs identiques.|Phoenix — Lignée de sorcières assassines reconnues par une marque de phénix, disposant de traditions et de compétences transmises dans le clan.
org-stillman|Les sœurs Stillman|coven familial|S06E04|Stillman_Sisters;The_Power_of_Three_Blondes|Mabel, Mitzy et Margo sont trois sorcières escroqueuses. Des opérations distinctes leur permettent d’usurper l’identité des Halliwell puis leurs pouvoirs. Leur rivalité interne affaiblit leur entreprise. Le recours à une potion de déplacement ne prouve pas une téléportation innée.|Le même symbole que celui du Triple Croissant ne démontre pas une affiliation. Dater les pouvoirs volés ; ne pas les conserver après leur restitution. L’identité usurpée et l’identité réelle doivent rester liées dans le catalogue.|Sœurs Stillman — Trio de sorcières pratiquant l’escroquerie et des sorts d’usurpation. Peuvent coordonner leur magie malgré leurs rivalités.
org-jenkins|Billie et Christy — Ultimate Power|sororité|S08E18,S08E21,S08E22|The_Ultimate_Power|La Triade et Dumain cherchent à utiliser les sœurs Jenkins contre les Halliwell. Christy, conditionnée depuis son enlèvement, entraîne Billie dans cette lecture du conflit. Billie comprend finalement la manipulation et s’oppose à Christy ; leur alliance prend fin.|Leur opposition n’est pas une nature maléfique innée. Les explications de Prue sur un Pouvoir des Trois incomplet appartiennent aux comics et sont exclues. Le titre Ultimate Power peut aussi désigner d’autres forces : conserver l’identité des sœurs.|Sœurs Jenkins — Duo de sorcières capables de conjuguer leurs pouvoirs. Leur lien familial et leurs convictions orientent une coopération qui peut évoluer.
org-eva|Coven d’Eva|coven historique|S03E04|Eva|En 1670, le coven protège Charlotte et l’enfant qui deviendra Melinda Warren. Eva et les autres utilisent la puissance de la nuit d’Halloween pour appeler les sœurs et leur transmettent des pratiques de magie naturelle utiles à cette époque.|Le nom du groupe est descriptif. Distinguer pratiques rituelles de ce coven et pouvoirs modernes des Halliwell. La protection de l’enfant motive leur action sans donner à tous une connaissance complète de la descendance future.|Coven d’Eva — Cercle de sorcières du XVIIe siècle maîtrisant des pratiques de magie naturelle et des rituels collectifs.
org-penny|Cercle de sorcières de Penny|coven historique|S06E11|Coven|Les souvenirs de la jeunesse de Penny montrent un cercle de sorcières et des réunions collectives, notamment dans Witchstock. Son histoire comprend aussi des relations ultérieures avec les anciennes participantes du club de bridge.|Intitulé descriptif ; effectif et continuité institutionnelle non établis. Le groupe de Gail recoupe ce réseau sans que la trahison de Gail puisse être attribuée à Penny. La chronologie familiale de Witchstock exige un contrôle spécifique avant datation fine.|Cercle de Penny — Réseau de sorcières entretenant des liens personnels et des pratiques collectives autour de Penny Halliwell.
org-gail|Coven de Gail, Helen et Amanda|coven|S02E17|Gail_Altman;Amanda|Anciennes connaissances de Penny, Gail, Helen et Amanda concluent avec Cryto un marché de rajeunissement. Elles trompent les sœurs pour s’emparer de leurs pouvoirs. Le marché se retourne contre elles, et Gail exprime des regrets.|Le trio constitue le groupe de cette intrigue, pas une preuve que tout le cercle historique de Penny serait maléfique. Leurs motivations personnelles ne rendent pas leurs pouvoirs permanents ni leur alliance avec Cryto sûre.|Coven de Gail — Trio de sorcières liées à l’ancien entourage de Penny, disposant de connaissances rituelles et de pratiques collectives.
org-janna|Coven de Janna|coven|S03E20|Janna|Janna appartient à un coven dont les connaissances en herbes et potions contribuent à préparer une aide pour Cole. Une partie d’une amulette est confiée à sa garde. Son implication la place sur la trajectoire de Raynor et de Belthazor.|La mort de Janna ne renseigne pas sur celle de tous les membres. La garde d’une moitié d’amulette ne garantit pas l’accès à l’autre. Direction et effectif complets restent insuffisamment documentés.|Coven de Janna — Cercle de sorcières disposant de connaissances en herboristerie et en préparation de potions, associé à la garde d’une amulette.
org-triple-croissant|Triple Crescent Coven — Triple Croissant|coven de pratiquants|S04E08|Triple_Crescent_Coven;Kari|Coven associé à Kari et Susan Coleman, identifié par un pendentif à trois croissants. La documentation distingue ses pratiques de celles de sorcières possédant des pouvoirs innés. Kari est victime de Sykes, qui vise des femmes ressemblant à sa cible.|Ne pas confondre pratique de sorcellerie et pouvoirs actifs héréditaires. Le motif des Stillman ne démontre pas une organisation commune. Traduction française de travail ; absence de pouvoirs innés rapportée pour ce groupe, pas pour tous les covens.|Triple Croissant — Coven de pratiquants de sorcellerie identifié par un pendentif à trois croissants, sans pouvoirs innés établis pour ses membres décrits.
org-montana|Famille Montana|clan familial|S06E05,S06E15|Montana_Family|Famille de sorciers engagée dans une longue vendetta avec les Callaway. Richard appartient à ce clan, qui conserve livres, ingrédients et potions. L’intrigue des deux familles montre l’épuisement d’une hostilité dont l’origine est devenue obscure et la recherche d’une paix.|Les capacités propres à Richard ne s’étendent pas à chacun. Sa renonciation personnelle à la magie ne supprime pas celle de sa famille. Une parenté ne garantit ni l’accord de tous ni la disponibilité de toutes les réserves.|Famille Montana — Clan de sorciers disposant d’un patrimoine de connaissances et de préparations magiques, marqué par sa rivalité avec les Callaway.
org-callaway|Famille Callaway|clan familial|S06E05|Callaway_Family|Clan de sorciers rival des Montana. Olivia, morte mais toujours attachée à Richard, intervient comme esprit et contribue à relancer la violence, y compris contre sa propre famille. La confrontation révèle des responsabilités plus complexes qu’une opposition simple entre deux camps.|Ne pas attribuer à toute la famille les actes d’Olivia ni sa capacité de possession. Certains prénoms secondaires proviennent des crédits ou du wiki et demandent contrôle. La trêve doit être datée avant de décrire leur politique actuelle.|Famille Callaway — Clan de sorciers engagé dans une histoire de rivalités avec les Montana, avec des positions individuelles qui peuvent diverger.
org-devlin|Groupe de Devlin|faction|S04E09|Muse_to_My_Ears/Plot;Muse_to_My_Ears/Script|Devlin tente de fédérer des warlocks pendant l’affaiblissement de la Source. Un anneau lui permet de capturer des muses afin d’exploiter leur inspiration. Sa brutalité envers les opposants montre un recrutement soumis à sa propre ambition.|Nom descriptif, sans raison sociale officielle. Les facultés de l’anneau ne sont pas des pouvoirs innés communs à la faction. La présence de muses captives n’en fait pas des adhérentes volontaires.|Groupe de Devlin — Faction de warlocks recrutés autour d’une ambition de pouvoir et de moyens permettant d’exploiter l’inspiration des muses.
org-kurzon|Partisans de Kurzon|faction|S04E14|Kurzon|Kurzon, ancien rival de la Source, revient avec des partisans et cherche à profiter d’un changement de pouvoir. La Voyante exploite ses ambitions et l’oriente vers les sœurs. Sa faction dépend de sa prétention au commandement.|Effectif et organigramme ne sont pas documentés. Les manipulations de la Voyante ne constituent pas une alliance sincère et durable. La mort du chef ne renseigne pas à elle seule sur chaque partisan.|Partisans de Kurzon — Faction démoniaque réunie autour d’un prétendant au pouvoir, disponible pour des opérations liées à ses ambitions.
org-zankou|Faction de Zankou|faction|S07E10,S07E13,S07E22|Zankou;Fight_for_the_Nexus|Des démons libèrent Zankou face à la menace des Avatars malgré les réticences d’autres démons. Une coopération temporaire avec les Halliwell vise à annuler Utopia ; Zankou devient ensuite leur adversaire dans la lutte pour le Nexus.|La coalition contre les Avatars ne fait pas de Zankou un allié durable. Ses capacités d’absorption sont personnelles. Les effectifs et relais changent : ne pas additionner tous les démons de la saison dans une armée disponible.|Faction de Zankou — Coalition démoniaque réunie autour d’un chef puissant, capable d’alliances tactiques et de mobilisations pour la conquête du pouvoir.
org-haas|Faction de Haas, Elkin et Black Heart|faction|S08E01,S08E02|Paul_Haas;Black_Heart|Après la disparition apparente des Halliwell et la chute de Zankou, des démons cherchent à occuper le Manoir comme symbole de domination. Haas, Elkin et Black Heart participent à ces entreprises ; des pièges utilisent des innocents pour faire réagir les sorcières.|Ne pas confondre conquête symbolique du Manoir et possession effective du Nexus. Les aptitudes d’Elkin et de Black Heart ne sont pas celles de tous leurs associés. Dater les pertes et changements de commandement.|Faction de Haas — Groupe démoniaque cherchant à occuper une position de pouvoir après la disparition apparente des Halliwell.
org-imara|Cellule d’Imara|cellule|S07E19|Imara|Imara et ses serviteurs observent les sœurs avant une opération fondée sur un échange d’âmes avec Phoebe. La chef convoite son apparence et ses pouvoirs ; ses relations avec ses subordonnés sont coercitives.|L’échange d’âmes est attribué à Imara, pas à tous ses agents. L’observation préparatoire ne leur donne pas accès aux pensées ni à chaque secret. Le nom de cellule est proposé pour classer cet entourage restreint.|Cellule d’Imara — Petit groupe démoniaque pratiquant la surveillance et l’infiltration sous l’autorité d’Imara.
org-katya|Cellule de Katya|cellule|S07E18|Katya|Katya et ses agents cherchent à contrôler la boîte de Pandore en manipulant ou capturant ses gardiennes. La documentation rattache son passé aux Dark Lords ; l’opération montrée est conduite autour de ses propres intérêts.|Ne pas confondre ses anciens maîtres avec tous ses agents actuels. La possession de la boîte est une situation à établir, pas un équipement permanent de chaque membre. Organigramme des Dark Lords non documenté dans ce lot.|Cellule de Katya — Agents démoniaques spécialisés dans une opération visant les gardiennes de la boîte de Pandore et le contrôle de cet objet.
org-vampires|Clans de vampires et leurs reines|clan|S04E18,S07E22|Vampire_Queen|La reine de saison 4 dirige un clan et cherche à rallier Paige. La mort de cette reine entraîne celle de ses vampires et interrompt la transformation encore inachevée de Paige. Une autre reine apparaît dans les négociations de Zankou en saison 7.|Deux reines à des périodes différentes ne constituent pas une même personne ni la preuve d’une administration mondiale. Le lien vital constaté dans le premier clan doit rester rattaché à ce cas. Exclure Lorna et les intrigues de Neena des comics.|Clan de vampires — Communauté placée sous l’autorité d’une reine, avec des liens de dépendance et des pratiques de transformation propres au clan concerné.
org-gideon|Intermédiaires et exécutants de Gideon|réseau clandestin|S06E16,S06E23|Gideon|Gideon emploie des intermédiaires, dont des Êtres des ténèbres, dans son projet caché contre Wyatt. Une opération contre Leo sert à l’écarter. Ce réseau clandestin est distinct de l’autorité publique que Gideon détient comme Fondateur.|Gideon n’est pas membre de l’espèce des Êtres des ténèbres. Un contrat ponctuel ne prouve pas que toute cette espèce lui obéit. Les membres du Conseil et les personnels de l’école ne connaissent pas automatiquement son projet.|Réseau de Gideon — Intermédiaires et exécutants liés à des missions clandestines commanditées par Gideon, avec des degrés variables d’information.
org-marche|Réseau du marché démoniaque|réseau économique|S05E16,S05E20|Demonic_Market;The_Crone|Le marché réunit vendeurs, acheteurs et intermédiaires autour de pouvoirs, objets et êtres captifs. La Crone y représente ou conseille des intérêts puissants et tente d’utiliser la question de Wyatt dans ses négociations. Il s’agit d’un réseau économique autant que d’un lieu.|Ne pas assimiler tous les commerçants à une seule faction ni un décret de la Crone à une obéissance universelle. Vente proposée, possession et authenticité d’une marchandise restent distinctes. Le lieu devrait être relié à une fiche de lieu séparée.|Marché démoniaque — Réseau d’échanges et d’intermédiaires proposant pouvoirs, objets et autres ressources magiques, soumis à des intérêts concurrents.
org-police|Police de San Francisco — dans la série|institution humaine|S01E22,S06E19,S07E22|San_Francisco_Police_Department|Institution d’enquête à laquelle appartiennent Andy, Darryl et Sheridan selon la période. Certains agents connaissent le secret des sœurs, d’autres enquêtent sur leurs anomalies. Le procès surnaturel de Darryl montre qu’une procédure peut reposer sur des événements magiquement falsifiés.|Ce sont les faits de la fiction, pas une description juridique du service réel. La confiance de Darryl ne donne pas accès à tout le service. Les dossiers et connaissances détenus par chaque agent doivent être distingués.|Police de San Francisco — Institution d’enquête disposant d’agents, de dossiers et de moyens ordinaires d’investigation ; la connaissance de la magie varie selon les personnes.
org-securite|Homeland Security — dans la série|institution humaine|S07E22,S08E05,S08E09|Homeland_Security;Russ_Murphy|Des agents fédéraux enquêtent sur les Halliwell et négocient avec elles. Murphy participe à leur retour public en saison 8. Hulkus Pocus révèle un programme impliquant du sang démoniaque dont les conséquences compromettent la coopération.|La connaissance de certains agents ne signifie pas que tout le gouvernement connaît la magie. Exclure les Magic Squads des comics. Ne pas inventer un organigramme réel ni confondre automatiquement cette agence avec le FBI.|Homeland Security — Service fédéral de la série disposant d’enquêteurs et d’informations sensibles ; certains agents entretiennent des contacts avec les Halliwell.
org-baymirror|The Bay Mirror|institution humaine|S04E16,S05E16|The_Bay_Mirror|Journal où Phoebe tient une chronique de conseils. Elise assure une fonction éditoriale et Jason intervient comme propriétaire à une période ultérieure. Le journal fournit un cadre professionnel, des lecteurs et des circuits d’information.|Journal ordinaire, pas organisation magique. L’emploi de Phoebe ne confère pas à toute la rédaction ses dons ou sa connaissance du surnaturel. Accès aux archives et publication dépendent des rôles et circonstances.|The Bay Mirror — Journal doté d’une rédaction, de chroniques et de réseaux d’information ; cadre professionnel de Phoebe.
org-buckland|Buckland Auction House|institution humaine|S01E01,S01E10|Buckland_Auction_House;%22Rex_Buckland%22|Maison de ventes où travaille Prue. Deux warlocks tuent Rex Buckland et Hannah Webster et usurpent leur identité afin de s’approcher des sœurs. L’infiltration exploite une institution humaine existante.|La société n’est pas intrinsèquement démoniaque parce que des dirigeants ont été remplacés. Distinguer victimes humaines et usurpateurs homonymes. Expertise d’objets anciens et certification de propriétés magiques ne sont pas équivalentes.|Buckland — Maison de ventes aux enchères disposant d’expertise et de circuits d’échange d’objets anciens et de collection.'''

rows=[]
for line in RAW.splitlines():
    fields=line.split('|')
    assert len(fields)==8, fields
    ident,name,kind,eps,src,facts,limits,card=fields
    rows.append(dict(id=ident,titre=name,typeCollectif=kind,episodesReperes=eps.split(','),pages=src.split(';'),canon=facts,limitesEtIncertitudes=limits,carteProposee=card))

existing={
'org-nettoyeurs':('org-nettoyeurs','La fiche décrivait l’effacement de Wyatt. Ajout du lien de subordination au Tribunal et de la réécriture incriminant Darryl ; sources The_Cleaners et transcription S06E19.'),
'org-tribunal':('org-tribunal','La fiche décrivait le conseil mixte. Ajout des fonctions distinctes des juges, de Gideon et de Barbas ; The_Tribunal et transcription S06E19. Maintien de l’exclusion des comics.'),
'org-confrerie':('org-confrerie','La fiche décrivait Cole, Vornac et Klea. Ajout du recrutement élitiste, de l’infiltration économique et du serment ; Brotherhood_of_the_Thorn. Réserve nouvelle sur les survivants et maintien de la réserve de traduction.'),
'org-avatars':('org-avatars','La fiche décrivait Utopia et le consentement. Ajout de la réserve collective, des adhésions à des périodes distinctes et de l’affaiblissement lié à Beta ; Avatars et Beta.'),
'org-fondateurs':('elders','Fiche collective déjà documentée dans personnages.json. Proposition de classement et de liaison ; préserver ses observations et sources plus fortes. The_Elders sert de complément de repérage, sans remplacer les faits déjà revus.'),
'org-triade':('triad','Deux occurrences dans personnages.json et magie-demons.json. Ajouter le repérage des membres tardifs et la distinction Dumain serviteur/candidat à l’admission ; The_Triad. Conserver les observations et transcriptions existantes sur les formes spirituelles.')}

sources={}
for row in rows:
    row['categorie']='organisations'
    row['activation']='non_active_contribution'
    row['sources']=[]
    for page in row.pop('pages'):
        key='wiki:'+page
        sources[key]={'url':'https://charmed.fandom.com/wiki/'+page,'niveau':'extrait_indexe_secondaire','consulteLe':'2026-09-08','portee':'Passages indexés utilisés pour la fiche ; accès direct intégral non certifié. Wiki de fans mêlant plusieurs médias : seuls les événements TV indiqués sont retenus.'}
        row['sources'].append(key)
    row['conditionsPourLeJeu']='Proposition de préparation : fixer la période, les représentants effectivement présents, leur information et leur coopération. Les capacités individuelles et les objets détenus ne deviennent pas des propriétés de tout le collectif.'
    row['origineAjustements']=existing.get(row['id'],(None,'Nouvelle fiche collective proposée dans ce dossier. Des membres ou événements peuvent déjà figurer dans les profils individuels ; aucune absence générale du projet n’est affirmée.'))[1]
    row['identifiantExistant']=existing.get(row['id'],(None,None))[0]
    row['niveau']='recherche_secondaire_partielle'
sources['ss:s06e19']={'url':'https://www.springfieldspringfield.co.uk/view_episode_scripts.php?episode=s06e19&tv-show=charmed','niveau':'transcription_non_officielle_passages_consultes','consulteLe':'2026-09-08','portee':'Passages 128–190 et 275–296 dans la vue consultée : Tribunal mixte, création des Nettoyeurs, réécriture, Gideon défense, Barbas adversaire. Pas de visionnage ni de certification du script.'}
for row in rows[:2]: row['sources'].append('ss:s06e19')

epindex=json.loads((ROOT/'Charmed/canon/episodes-index.json').read_text(encoding='utf-8-sig'))
episodes={e['id']:e for e in epindex['episodes']}
assert len({r['id'] for r in rows})==len(rows)
assert all(e in episodes for r in rows for e in r['episodesReperes'])
assert all(s in sources for r in rows for s in r['sources'])
assert all(r[k] for r in rows for k in ['id','titre','typeCollectif','canon','limitesEtIncertitudes','carteProposee','origineAjustements'])
old_research=json.loads((ROOT/'Charmed/recherche/2026-09-08-organisations-phenomenes-enquetes/fiches.json').read_text(encoding='utf-8-sig'))
old_characters=json.loads((ROOT/'Charmed/canon/personnages.json').read_text(encoding='utf-8-sig'))
old_ids={r['id'] for r in old_research['fiches']}|{r['id'] for r in old_characters['characters']}
assert all(value[0] in old_ids for value in existing.values())
lot={'version':1,'universe':'charmed-tv-1998','status':'contribution_documentaire_a_revoir','date':'2026-09-08','preuve':'Recherche web réelle principalement par extraits indexés secondaires ; passages d’une transcription non officielle consultés pour S06E19 ; aucun épisode visionné. Pas d’exhaustivité certifiée.','exclusions':['reboot 2018','comics','romans','fanfiction'],'sources':sources,'fiches':rows}
(HERE/'organisations.json').write_text(json.dumps(lot,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
with (HERE/'CATALOGUE_ORGANISATIONS.tsv').open('w',encoding='utf-8-sig',newline='') as f:
    cols=['id','titre','typeCollectif','episodesReperes','canon','limitesEtIncertitudes','carteProposee','identifiantExistant','origineAjustements','sources']
    w=csv.DictWriter(f,fieldnames=cols,delimiter='\t',extrasaction='ignore');w.writeheader()
    for row in rows:
        item=dict(row);item['episodesReperes']=' ; '.join(row['episodesReperes']);item['sources']=' ; '.join(sources[s]['url']+' ['+sources[s]['niveau']+']' for s in row['sources']);w.writerow(item)

intro='''# Proposition à intégrer — Organisations de Charmed

**Contribution : organisations. Date : 8 septembre 2026. Statut : proposition documentaire à examiner, non intégrée par cette contribution.**

## Demande traitée

Rechercher largement les organisations de la série originale, saisons 1 à 8, indiquer d’où proviennent les informations et, lorsqu’une fiche existe déjà, d’où viennent les ajustements. Le présent catalogue rassemble institutions, covens, clans, ordres, factions et réseaux effectivement identifiables. Les petites cellules portent des noms descriptifs explicitement proposés. Quatre institutions humaines de la fiction sont séparées par leur type. Une espèce entière n’est pas assimilée automatiquement à une organisation.

La recherche vise une couverture large des principaux ensembles et de nombreux groupes ponctuels. Elle ne dispose pas d’un dénominateur exhaustif permettant de certifier « tous » ou un pourcentage de la majorité des organisations de 178 épisodes. Les épisodes indiqués sont des repères contextualisés, pas un relevé complet des apparitions.

## Instructions et fichiers consultés

- Instructions globales canoniques : `C:\\Users\\auror\\Documents\\Codex\\2026-08-29\\dis-moi-est-ce-que-tu\\outputs\\01_REGLES_GLOBALES_ACTEES.md` ; instructions AGENTS fournies dans la conversation, sans fichier AGENTS local trouvé.
- `Charmed/REGLES_ACTEES.md`, `Charmed/DECISIONS_ACTEES.md`, `Charmed/BIBLIOTHEQUE.md`, `Charmed/PREPARATION_DOCUMENTEE.md` : décisions et préparation documentaire.
- `Charmed/recherche/2026-09-08-organisations-phenomenes-enquetes/FICHES.md` et les quatre fiches organisations de `fiches.json` : Nettoyeurs, Tribunal, Confrérie, Avatars.
- `Charmed/canon/personnages.json` : fiches collectives elders et triad, repérages des liens de Gideon, Cole, Leo et Christy ; `Charmed/canon/PERSONNAGES_DETAILLES.md` : section Fondateurs.
- `Charmed/canon/magie-demons.json` : fiche triad ; `Charmed/canon/construction.json` : repérage ; `Charmed/canon/episodes-index.json` : contrôle des identifiants et titres d’épisodes, pas preuve du contenu.
- `Charmed/canon/contributions-integrees/manifest.json` et `serveur/charmed/bibliotheque.js` : manifeste et chemins effectivement chargés.

Les titres anciens « recherche non active » ne décrivent pas nécessairement l’usage actuel : le chargeur lit les dossiers de recherche. Le manifeste et la bibliothèque témoignent d’intégrations antérieures d’autres contributions. Ce dossier-ci reste hors de ces chemins de chargement.

## Constats et proposition d’intégration

Six collectifs ont une correspondance de fiche identifiée : les quatre du lot organisations, les Fondateurs et la Triade. La Triade apparaît dans deux fichiers canoniques. Les textes ci-dessous sont des compléments proposés : les observations déjà revues et leurs sources plus fortes doivent être conservées. Ne pas remplacer globalement une fiche par un résumé de wiki moins vérifié.

Les fiches distinguent le savoir destiné à l’Ange du destin et la description courte de carte. Les conditions de scénario sont des propositions d’usage, pas de nouvelles règles actées. Les cartes décrivent les propriétés du collectif ; elles ne fournissent ni scénario de victoire ni droit automatique à ses membres, pouvoirs, archives et objets.

Le JSON utilise les champs des fiches de recherche existantes et ajoute type, correspondance, carte et sources multiples. Il s’agit d’un format documentaire de contribution, pas d’un import prêt à exécuter. Aucun patch n’est appliqué.

## Sources et niveaux réels de vérification

Les URL de chaque fiche indiquent exactement d’où viennent ses faits et ajouts. Le wiki Charmed a été interrogé sur ses pages de groupes, de personnages, d’épisodes et de catégories ; les extraits effectivement retournés ont été lus. Des ouvertures directes Fandom ont échoué, notamment Brotherhood of the Thorn : aucun accès intégral n’est certifié. Des résultats longs restent classés « extrait indexé secondaire ». Une transcription de S06E19 sur Springfield a été ouverte et ses passages pertinents lus ; elle demeure non officielle. Aucun épisode n’a été visionné, aucune version française n’a été auditée. Le niveau de preuve antérieur des sources locales n’est pas réattribué à la présente recherche.

Les références d’une fiche soutiennent les faits et le contexte du paragraphe « Connaissances ». Le paragraphe « Limites » distingue réserves documentaires et précautions de transposition. Les formulations de cartes et catégories sont des propositions éditoriales de ce dossier.

## Contradictions, exclusions et arbitrages

1. **Conseil / Triade / conseil des couronnements :** la continuité est hypothétique. L’annotation « later known as The Triad » d’une transcription de S02E22 n’est pas une réplique. Garder les entrées distinctes avant arbitrage explicite.
2. **Confrérie :** descriptions incompatibles du nombre de survivants dans la même page, notamment Klea et Jassa. Ne pas annoncer l’anéantissement complet.
3. **Ordre :** croire Wyatt réincarné n’en fait pas une vérité. Les pouvoirs d’une page de Livre des Ombres signalée comme inutilisée à l’écran ne doivent pas être promus en faits TV ; des fuyards rendent « détruit » trop catégorique.
4. **Phoenix :** marque de naissance dans la page dédiée, parfois qualifiée de tatouage dans une description générique des covens. Préférer provisoirement la source dédiée, conserver le contrôle visuel à faire.
5. **Stillman / Triple Croissant :** symbole ressemblant, affiliation non démontrée. **Académies Kellman / Ludlow :** publics et méthodes distincts, pas de fusion fondée sur le mot académie.
6. **Puissance et hiérarchie :** les mots illimité, invincible, immortel ou tous les démons ne doivent pas effacer les coûts, destructions, dissidences et exceptions effectivement rapportés.
7. **Comics et romans exclus :** [Witch Council](https://charmed.fandom.com/wiki/Witch_Council), [Magic Squads](https://charmed.fandom.com/wiki/Magic_Squads), nouveau Tribunal et massacre associé, ailes de la Halliwell Academy, explication posthume de Prue sur l’Ultimate Power. [Gathering of the Covens](https://charmed.fandom.com/wiki/Gathering_of_the_Covens) relève d’un roman. Ces pages ont été repérées par extraits indexés, pas validées comme faits TV. La Faction du reboot est hors périmètre.
8. **Classement à décider :** faut-il afficher les clans familiaux et petites cellules comme cartes d’organisation, ou conserver certaines fiches uniquement en connaissances ? Les institutions humaines sont proposées en annexe typée. Aucun changement de catégorie active n’est effectué ici.
9. **Autorités du jeu :** Tribunal et Fondateurs appartiennent à la fiction ; ils ne sont pas l’Ange du destin qui arbitre l’interface. Les règles d’accès, coopération et ressources effectivement disponibles restent celles actées dans le projet.

## Fichiers qui seraient concernés par une intégration

- Compléments ciblés des quatre entrées de `Charmed/recherche/2026-09-08-organisations-phenomenes-enquetes/fiches.json` et de son `FICHES.md`, si cette voie est retenue.
- Liaison et dédoublonnage de `elders` et `triad` dans `Charmed/canon/personnages.json`, `Charmed/canon/PERSONNAGES_DETAILLES.md` et de `triad` dans `Charmed/canon/magie-demons.json`.
- Nouveau dossier documentaire revu, éventuellement dans `Charmed/canon/contributions-integrees/`, déclaré dans son `manifest.json`. Choisir une voie cohérente pour ne pas charger deux copies concurrentes.
- `Charmed/BIBLIOTHEQUE.md` pour le repérage ; `Charmed/canon/bibliotheque-verifiee.json` seulement pour les assertions effectivement revues par la conversation principale. Aucun fait n’est automatiquement promu « vérifié » par ce catalogue.
- Pas de modification requise des règles de jeu ni du serveur pour la seule remise de cette proposition. Les sauvegardes restent hors périmètre.

## Vérifications effectuées et travail restant

Contrôles automatiques : unicité des identifiants ; références de sources résolues ; épisodes présents dans l’index local ; champs renseignés ; six correspondances aux fiches existantes ; cohérence des nombres JSON/TSV/Markdown. Le résultat figure dans `VERIFICATIONS.json`. Ces contrôles sont structurels et ne certifient pas le canon.

Travail restant avant intégration : revue des compléments contre les sources déjà plus fortes ; vérification à l’écran des points litigieux, des appellations françaises, des pouvoirs individuels et des chronologies fines ; choix du périmètre de représentation de chaque carte ; arbitrage des rapprochements de collectifs. Compléter au besoin les groupes moins documentés, notamment les Dark Lords, autres communautés de créatures, lignées périphériques et petites factions épisodiques. Le futur dossier de partie doit encore contrôler les interactions précises qu’il utilisera.

Tous les fichiers écrits par cette contribution sont dans `Charmed/contributions/organisations/`. Aucun serveur ni jeu n’a été lancé ou redémarré. Aucun fichier actif ou de sauvegarde n’a été modifié par cette contribution.

'''
md=[intro,f'## Catalogue : {len(rows)} fiches et {len(rows)} propositions de carte\n\n| N° | Collectif | Type | Correspondance existante |\n| --- | --- | --- | --- |']
for i,r in enumerate(rows,1):md.append(f"| {i:02} | {r['titre']} | {r['typeCollectif']} | {r['identifiantExistant'] or 'non identifiée comme fiche collective dédiée'} |")
for i,r in enumerate(rows,1):
    refs=' ; '.join(f"{e} — {episodes[e]['title']}" for e in r['episodesReperes'])
    md.extend([f"\n## {i:02}. {r['titre']}\n",f"**Identifiant proposé :** `{r['id']}`. **Type :** {r['typeCollectif']}.\n",f"**Épisodes repères :** {refs}.\n",f"**D’où viennent l’ajout ou les ajustements :** {r['origineAjustements']}\n",'### Fiche détaillée — Ange du destin\n',f"**Connaissances et contexte :** {r['canon']}\n",f"**Limites, variantes et incertitudes :** {r['limitesEtIncertitudes']}\n",f"**Conditions de transposition proposées :** {r['conditionsPourLeJeu']}\n",'**Sources de ces informations :**\n'])
    for s in r['sources']:md.append(f"- [{s}]({sources[s]['url']}) — {sources[s]['niveau']}. {sources[s]['portee']}")
    md.extend(['\n### Description courte proposée pour la carte\n',r['carteProposee']+'\n'])
md.append('\n## Registre des sources\n')
for key,s in sources.items():md.append(f"- [{key}]({s['url']}) — {s['niveau']} ; consultation {s['consulteLe']}.")
(HERE/'PROPOSITION_A_INTEGRER.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
with (HERE/'CATALOGUE_ORGANISATIONS.tsv').open(encoding='utf-8-sig',newline='') as f:
    exported=list(csv.DictReader(f,delimiter='\t'))
assert len(exported)==len(rows)
assert [r['id'] for r in exported]==[r['id'] for r in rows]
rendered=(HERE/'PROPOSITION_A_INTEGRER.md').read_text(encoding='utf-8')
assert rendered.count('### Fiche détaillée — Ange du destin')==len(rows)
assert rendered.count('### Description courte proposée pour la carte')==len(rows)
report={'fiches':len(rows),'cartes':len(rows),'sourcesFiches':len(sources),'episodesDistincts':len({e for r in rows for e in r['episodesReperes']}),'correspondancesExistantes':len(existing),'idsUniques':True,'sourcesResolues':True,'episodesDansIndex':True,'validationCanonique':'non_effectuee_par_les_controles_structurels','fichiers':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in HERE.iterdir() if p.is_file() and p.name!='VERIFICATIONS.json'}}
(HERE/'VERIFICATIONS.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({k:v for k,v in report.items() if k!='fichiers'},ensure_ascii=False))
