const fs=require('fs'),path=require('path');
const dest=path.resolve(__dirname,'../Charmed/visuels/cinq-directions');
const origin='C:/Users/auror/.codex/generated_images/01a07c97-fcdc-76b0-9e69-6f593b6a159c';
const designs=[
 ['01-livre-des-ombres','Livre des Ombres','Cuir vert, parchemin et dessin du grenier.','exec-d1655d25-5988-409e-8e60-6eebc9f7cd80.png'],
 ['02-grenier-bougies','Grenier à la bougie','Bois sombre, photographie du grenier et lumière chaude.','exec-c04f0ba8-52ec-4f31-abfb-40e18fef748f.png'],
 ['03-vitraux-manoir','Vitraux du manoir','Bordures de vitraux, lumière claire et gravures du manoir.','exec-8242f9e5-0a0d-4844-b907-c4f076127fec.png'],
 ['04-charmed-nocturne','Charmed de nuit','Grenier nocturne, prune sombre et texte ivoire.','exec-5e7ac76a-ca9a-4ac8-8f8a-b948d1a48aa6.png'],
 ['05-pages-sorcellerie','Pages de sorcellerie','Pages anciennes, dessins botaniques et encre sépia.','exec-7d65b7f9-67be-4c3d-9b07-ce86317f5415.png'],
 ['06-mal-halliwell','Mal / Halliwell — proposition supplémentaire','En haut, un décor sombre évoquant le Mal ; en bas, le grenier des sœurs.','exec-82eded8a-0f32-4cc7-a2ad-a0b3bb780a48.png']
];
for(const d of designs)fs.copyFileSync(path.join(origin,d[3]),path.join(dest,d[0]+'.png'));
fs.writeFileSync(path.join(dest,'selection.json'),JSON.stringify(designs.map((d,i)=>({number:i+1,id:d[0],title:d[1],description:d[2],source:path.join(origin,d[3]),file:d[0]+'.png',status:'proposition_non_integree'})),null,2));
const cards=designs.map((d,i)=>`<article><h2>${i+1}. ${d[1]}</h2><p>${d[2]}</p><a href="${d[0]}.png" target="_blank"><img src="${d[0]}.png" alt="Proposition ${i+1} : ${d[1]}" loading="eager"></a><a class="full" href="${d[0]}.png" target="_blank">Ouvrir en grand ↗</a></article>`).join('\n');
fs.writeFileSync(path.join(dest,'comparatif.html'),`<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Charmed — six propositions de décor</title><style>*{box-sizing:border-box}body{margin:0;background:#10271f;color:#f5ead1;font:16px/1.5 Georgia,serif}header{padding:22px 4vw;border-bottom:1px solid #a58b55;background:#091911}h1{margin:0;font-size:29px;font-weight:normal}header p{max-width:1050px;color:#d2c3a3}main{padding:24px 4vw;display:grid;grid-template-columns:1fr 1fr;gap:28px}article{min-width:0}h2{font-size:21px;margin:0 0 5px}article p{margin:0 0 12px;color:#d2c3a3}img{width:100%;display:block;border:1px solid #a58b55}a{color:#ecd394}.full{display:inline-block;margin-top:8px}footer{padding:20px 4vw;background:#091911;color:#d2c3a3}button{background:#ece0c3;color:#173629;border:1px solid #ae9256;padding:9px 14px;cursor:pointer;font:inherit}body.large main{grid-template-columns:1fr}@media(max-width:900px){main{grid-template-columns:1fr}}</style><header><h1>Charmed — cinq directions + une variante Mal / Halliwell</h1><p>Maquettes de direction artistique. États et sous-états verts ; triquetra en bas à droite. La séparation des décors Mal / Halliwell est proposée uniquement dans la sixième version.</p><button onclick="document.body.classList.toggle('large');this.textContent=document.body.classList.contains('large')?'Comparer deux par deux':'Voir une proposition par ligne'">Voir une proposition par ligne</button></header><main>${cards}</main><footer>Les images sont générées : leurs petits textes, symboles de statut et chaînes ne font pas foi pour les règles. La disposition mécanique, les attaques et les contenus exacts seront repris du code du jeu lors de l'intégration de la direction choisie. Le motif végétal sous Les Fondateurs fourni ensuite par Aurore est une piste à combiner avec le décor choisi. Aucun changement de la partie en cours.</footer></html>`);
fs.writeFileSync(path.join(dest,'README.md'),`# Propositions de décor Charmed\n\nCinq directions demandées, plus une sixième variante Mal / Halliwell. Images produites avec l'outil intégré image_gen. Les fichiers *-prompt.txt consignent les instructions initiales ; les variantes finales 1 et 2 déplacent uniquement la triquetra en bas à droite, les variantes 3 et 4 rétablissent un décor commun aux camps. La séparation Mal / Halliwell n'est conservée que dans la variante 6.\n\nCe sont des maquettes artistiques, pas des captures du moteur. Les petits textes générés (notamment Faux parfois rendu Fixe), les statuts, les verrous ajoutés et les zones d'attaque ne sont pas une spécification de jeu. Lors de l'intégration, conserver les données et les mécanismes du vrai plateau. Les dessins évoquent des lieux et ne constituent pas des documents canoniques. Les deux camps doivent rester visibles et seules leurs zones intérieures défilent.\n\nDécision de couleur utilisateur : états initiaux et sous-états verts, couleur du Livre des Ombres. Clés jaunes et verrous rouges. Le code du jeu n'a pas été modifié à cette étape.\n\nLa dernière inspiration (triquetra fine et végétaux sous Les Fondateurs) est appréciée comme piste graphique ; elle n'est pas encore appliquée à toutes les maquettes et ne modifie pas les règles du bulletin.\n\nOuvrir comparatif.html pour consulter les six propositions.\n`);
console.log(dest);
