const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),assets=path.join(root,'ecrans/modules/charmed-assets');
fs.mkdirSync(assets,{recursive:true});
for(const [source,dest] of [['Logo.png','logo.png'],['grenier.png','grenier.png']])fs.copyFileSync(path.join(root,'Charmed/visuels/Assets',source),path.join(assets,dest));
const htmlPath=path.join(root,'ecrans/charmed.html'),jsPath=path.join(root,'ecrans/modules/charmed.js');
const backup=path.join(root,'Charmed/visuels/assemblage-selection/avant-integration');fs.mkdirSync(backup,{recursive:true});
for(const f of ['ecrans/charmed.html','ecrans/modules/charmed.js','ecrans/modules/charmed.css'])if(!fs.existsSync(path.join(backup,path.basename(f))))fs.copyFileSync(path.join(root,f),path.join(backup,path.basename(f)));
let html=fs.readFileSync(htmlPath,'utf8');
html=html.replace('</head>','<link rel="stylesheet" href="/modules/charmed-skin.css?v=selection-b-1"></head>');
html=html.replace(/<header class="masthead">[\s\S]*?<\/header>/,`<header class="masthead"><div class="brand"><span id="game-title">Avant que la vision s’accomplisse</span></div><section class="facts" id="facts" aria-label="Faits établis"></section><div class="charmed-logo" role="img" aria-label="Charmed"></div><span id="phase" hidden></span></header>`);
html=html.replace('<h2>📻 Radio Halliwell</h2>','<h2 class="illuminated"><span class="initial">L</span>es Fondateurs</h2><p class="morning-label">Le message du matin</p>');
html=html.replace('<h2>🗓 Calendrier de la partie</h2>','<h2 class="illuminated"><span class="initial">C</span>alendrier<br><span class="subtitle">de la partie</span></h2>');
html=html.replace('<p class="calendar-note">Toute la partie · sélectionne un jour.</p>','<p class="calendar-note"><span id="day"></span> · sélectionne un jour.</p>');
html=html.replace(/<details class="rules">[\s\S]*?<\/details>/,'');
html=html.replace('<section class="facts" id="facts"></section>','');
html=html.replace('<section class="turn-panel"><h2>Le tour</h2>','<section class="turn-panel"><h2 class="illuminated"><span class="initial">L</span>e tour</h2>');
html=html.replace('<section><h2>⚖️ L’arbitre</h2><div id="arbitration"></div></section>',`<section class="arbiter-page"><h2 class="illuminated"><span class="initial">L</span>’Arbitre</h2><div id="arbitration"></div><div class="triquetra" aria-hidden="true"><svg viewBox="0 0 120 112"><defs><linearGradient id="knot-gold" x2=".8" y2="1"><stop stop-color="#f4d582"/><stop offset=".5" stop-color="#b28032"/><stop offset="1" stop-color="#e6bc61"/></linearGradient></defs><path class="knot-shadow" d="M60 8C25 37 27 72 60 79C93 72 95 37 60 8Z M14 94C57 109 86 87 75 53C53 27 21 43 14 94Z M106 94C99 43 67 27 45 53C34 87 63 109 106 94Z"/><path class="knot-gold" d="M60 8C25 37 27 72 60 79C93 72 95 37 60 8Z M14 94C57 109 86 87 75 53C53 27 21 43 14 94Z M106 94C99 43 67 27 45 53C34 87 63 109 106 94Z"/></svg></div></section>`);
html=html.replace('/modules/charmed.js?v=grimoire2','/modules/charmed.js?v=selection-b-1');
fs.writeFileSync(htmlPath,html);
let js=fs.readFileSync(jsPath,'utf8');
js=js.replaceAll('Radio Halliwell','Les Fondateurs').replaceAll('RADIO HALLIWELL','LES FONDATEURS').replaceAll('📻 LES FONDATEURS','LES FONDATEURS');
js=js.replace("const rules=document.querySelector('.rules');const rulesText=[...rules.querySelectorAll('p')].map(p=>p.textContent).join('\\n\\n');rules.replaceWith(button('Les règles',()=>readPages('Les règles actées',rulesText),false,'rules-button'));",'');
fs.writeFileSync(jsPath,js);
console.log('Skin markup and supplied assets installed; no game-state changes.');
